<a href="https://colab.research.google.com/github/Shubangi-sharma/SIH-PROJECT/blob/main/nasa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
north_file = "/content/drive/MyDrive/DataSetForpython/northern_osm_features.csv"
west_file = "/content/drive/MyDrive/DataSetForpython/western_zone_osm_fire_context.csv"

north_osm = pd.read_csv(north_file)
west_osm = pd.read_csv(west_file)

print("North OSM:", north_osm.shape)
print("West OSM :", west_osm.shape)

/tmp/ipykernel_1661/4132666507.py:4: DtypeWarning: Columns (7,8,9,10,11,12,14,15,16,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  north_osm = pd.read_csv(north_file)

North OSM: (92549, 32)
West OSM : (32909, 9)

In [ ]:
print("NORTH REGION")
print("Latitude :", north_osm["latitude"].min(), "to", north_osm["latitude"].max())
print("Longitude:", north_osm["longitude"].min(), "to", north_osm["longitude"].max())

print("\nWEST REGION")
print("Latitude :", west_osm["latitude"].min(), "to", west_osm["latitude"].max())
print("Longitude:", west_osm["longitude"].min(), "to", west_osm["longitude"].max())

NORTH REGION
Latitude : 23.015321 to 35.603247
Longitude: 69.2328816148548 to 79.473024292358

WEST REGION
Latitude : 14.90536962 to 24.51767769
Longitude: 68.501592 to 80.56554985

In [ ]:
import pandas as pd

# =========================
# REGION BOUNDING BOXES
# =========================

# North Region
NORTH_LAT_MIN = 23.015321
NORTH_LAT_MAX = 35.603247
NORTH_LON_MIN = 69.2328816148548
NORTH_LON_MAX = 79.473024292358

# West Region
WEST_LAT_MIN = 14.90536962
WEST_LAT_MAX = 24.51767769
WEST_LON_MIN = 68.501592
WEST_LON_MAX = 80.56554985


# =========================
# LOAD FIRMS DATA
# =========================

firms = pd.read_csv("/content/drive/MyDrive/DataSetForpython/fire(1).csv")

print("Total FIRMS records:", len(firms))
print("Columns:", list(firms.columns))


# =========================
# FILTER NORTH
# =========================

north_firms = firms[
    (firms["LATITUDE"] >= NORTH_LAT_MIN) &
    (firms["LATITUDE"] <= NORTH_LAT_MAX) &
    (firms["LONGITUDE"] >= NORTH_LON_MIN) &
    (firms["LONGITUDE"] <= NORTH_LON_MAX)
].copy()


# =========================
# FILTER WEST
# =========================

west_firms = firms[
    (firms["LATITUDE"] >= WEST_LAT_MIN) &
    (firms["LATITUDE"] <= WEST_LAT_MAX) &
    (firms["LONGITUDE"] >= WEST_LON_MIN) &
    (firms["LONGITUDE"] <= WEST_LON_MAX)
].copy()


# =========================
# SAVE RESULTS
# =========================

north_firms.to_csv("north_firms.csv", index=False)
west_firms.to_csv("west_firms.csv", index=False)


# =========================
# BASIC VERIFICATION
# =========================

print("\n========== RESULTS ==========")

print("\nNORTH REGION")
print("Records:", len(north_firms))
print("Date:", north_firms["ACQ_DATE"].min(), "to", north_firms["ACQ_DATE"].max())

print("\nWEST REGION")
print("Records:", len(west_firms))
print("Date:", west_firms["ACQ_DATE"].min(), "to", west_firms["ACQ_DATE"].max())

print("\nFiles created:")
print("north_firms.csv")
print("west_firms.csv")

Total FIRMS records: 1198688
Columns: ['LATITUDE', 'LONGITUDE', 'BRIGHTNESS', 'SCAN', 'TRACK', 'ACQ_DATE', 'ACQ_TIME', 'SATELLITE', 'INSTRUMENT', 'CONFIDENCE', 'VERSION', 'BRIGHT_T31', 'FRP', 'DAYNIGHT', 'TYPE']

========== RESULTS ==========

NORTH REGION
Records: 244392
Date: 2024/01/01 to 2025/12/31

WEST REGION
Records: 360388
Date: 2024/01/01 to 2025/12/31

Files created:
north_firms.csv
west_firms.csv

In [ ]:
print("===== NORTH TYPE =====")
print(north_firms["TYPE"].value_counts())

print("\n===== WEST TYPE =====")
print(west_firms["TYPE"].value_counts())

print("\n===== NORTH CONFIDENCE =====")
print(north_firms["CONFIDENCE"].value_counts())

print("\n===== WEST CONFIDENCE =====")
print(west_firms["CONFIDENCE"].value_counts())

===== NORTH TYPE =====
TYPE
0    238459
2      5882
3        51
Name: count, dtype: int64

===== WEST TYPE =====
TYPE
0    339286
2     20920
3       182
Name: count, dtype: int64

===== NORTH CONFIDENCE =====
CONFIDENCE
n    189623
l     45823
h      8946
Name: count, dtype: int64

===== WEST CONFIDENCE =====
CONFIDENCE
n    267386
l     83949
h      9053
Name: count, dtype: int64

In [ ]:
print("========== NORTH ==========")

print("\nTYPE:")
print(north_firms["TYPE"].value_counts())

print("\nCONFIDENCE:")
print(north_firms["CONFIDENCE"].value_counts())

print("\nDAY/NIGHT:")
print(north_firms["DAYNIGHT"].value_counts())

print("\nFRP:")
print(north_firms["FRP"].describe())


print("\n\n========== WEST ==========")

print("\nTYPE:")
print(west_firms["TYPE"].value_counts())

print("\nCONFIDENCE:")
print(west_firms["CONFIDENCE"].value_counts())

print("\nDAY/NIGHT:")
print(west_firms["DAYNIGHT"].value_counts())

print("\nFRP:")
print(west_firms["FRP"].describe())

========== NORTH ==========

TYPE:
TYPE
0    238459
2      5882
3        51
Name: count, dtype: int64

CONFIDENCE:
CONFIDENCE
n    189623
l     45823
h      8946
Name: count, dtype: int64

DAY/NIGHT:
DAYNIGHT
D    186252
N     58140
Name: count, dtype: int64

FRP:
count    244392.000000
mean          5.955835
std           7.435431
min           0.090000
25%           2.110000
50%           3.990000
75%           7.190000
max         265.430000
Name: FRP, dtype: float64


========== WEST ==========

TYPE:
TYPE
0    339286
2     20920
3       182
Name: count, dtype: int64

CONFIDENCE:
CONFIDENCE
n    267386
l     83949
h      9053
Name: count, dtype: int64

DAY/NIGHT:
DAYNIGHT
D    262421
N     97967
Name: count, dtype: int64

FRP:
count    360388.000000
mean          5.102252
std           5.674686
min           0.000000
25%           1.930000
50%           3.650000
75%           6.320000
max         243.560000
Name: FRP, dtype: float64

In [ ]:

# Add region labels
north_firms["REGION"] = "NORTH"
west_firms["REGION"] = "WEST"

# Merge
firms_master = pd.concat(
    [north_firms, west_firms],
    ignore_index=True
)

# Save master dataset
firms_master.to_csv(
    "firms_study_regions.csv",
    index=False
)

print("Master FIRMS dataset created!")
print("Total records:", len(firms_master))
print("\nRegion distribution:")
print(firms_master["REGION"].value_counts())

Master FIRMS dataset created!
Total records: 604780

Region distribution:
REGION
WEST     360388
NORTH    244392
Name: count, dtype: int64

In [ ]:
!pip -q install h3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 35.1 MB/s eta 0:00:00

In [ ]:
import h3

def get_h3_cell(row):
    return h3.latlng_to_cell(
        row["LATITUDE"],
        row["LONGITUDE"],
        9
    )

firms_master["H3_CELL"] = firms_master.apply(
    get_h3_cell,
    axis=1
)

print(firms_master[[
    "LATITUDE",
    "LONGITUDE",
    "H3_CELL"
]].head())

print("Unique spatial cells:",
      firms_master["H3_CELL"].nunique())

   LATITUDE  LONGITUDE          H3_CELL
0  28.75529   78.03030  893daccc253ffff
1  28.62116   78.20617  893dac55adbffff
2  32.11346   77.28508  893d1591893ffff
3  32.11057   77.28300  893d159189bffff
4  32.11166   77.28732  893d1591883ffff
Unique spatial cells: 468436

In [ ]:
firms_master["H3_CELL_8"] = firms_master.apply(
    lambda row: h3.latlng_to_cell(
        row["LATITUDE"],
        row["LONGITUDE"],
        8
    ),
    axis=1
)

print(
    "Unique H3 resolution-8 cells:",
    firms_master["H3_CELL_8"].nunique()
)

Unique H3 resolution-8 cells: 302103

In [ ]:
!pip -q install scikit-learn

In [ ]:
from sklearn.cluster import DBSCAN

In [ ]:
coords = firms_master[["LATITUDE", "LONGITUDE"]].to_numpy()

# Convert degrees → radians
coords_rad = np.radians(coords)

print("Total points:", len(coords_rad))

Total points: 604780

In [ ]:
# Earth's radius in metres
EARTH_RADIUS_M = 6_371_000

# 500 metre neighbourhood
EPS_METERS = 500
EPS_RAD = EPS_METERS / EARTH_RADIUS_M

dbscan = DBSCAN(
    eps=EPS_RAD,
    min_samples=2,
    metric="haversine",
    algorithm="ball_tree",
    n_jobs=-1
)

labels = dbscan.fit_predict(coords_rad)

firms_master["HOTSPOT_ID"] = labels

print("DBSCAN completed!")
print("Total clusters:", len(set(labels)) - (1 if -1 in labels else 0))
print("Noise points:", (labels == -1).sum())

DBSCAN completed!
Total clusters: 98584
Noise points: 133543

In [ ]:
# Convert acquisition date to proper date format
firms_master["ACQ_DATE"] = pd.to_datetime(
    firms_master["ACQ_DATE"]
)

# Ignore DBSCAN noise
clustered = firms_master[
    firms_master["HOTSPOT_ID"] != -1
].copy()

# Calculate persistence statistics
hotspot_stats = clustered.groupby("HOTSPOT_ID").agg(
    total_detections=("HOTSPOT_ID", "size"),
    unique_days=("ACQ_DATE", "nunique"),
    first_detection=("ACQ_DATE", "min"),
    last_detection=("ACQ_DATE", "max"),
    mean_FRP=("FRP", "mean"),
    max_FRP=("FRP", "max")
).reset_index()

print("Candidate hotspots:", len(hotspot_stats))
print(hotspot_stats.head())

Candidate hotspots: 98584
   HOTSPOT_ID  total_detections  unique_days first_detection last_detection  \
0           0                 2            2      2024-01-01     2024-12-17
1           1                 7            3      2024-01-01     2024-11-20
2           2                11            4      2024-01-01     2024-05-16
3           3                 9            5      2024-01-01     2025-02-12
4           4                 9            4      2024-01-01     2025-12-19

   mean_FRP  max_FRP
0  2.180000     2.34
1  6.912857     8.78
2  4.215455     8.65
3  3.256667     7.08
4  4.885556    15.36

In [ ]:
print(hotspot_stats["unique_days"].describe())

count    98584.000000
mean         2.293749
std          6.364972
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max        578.000000
Name: unique_days, dtype: float64

In [ ]:
print(hotspot_stats["unique_days"].value_counts().sort_index().head(20))

unique_days
1     44456
2     32484
3     10545
4      4583
5      2379
6      1278
7       745
8       548
9       327
10      230
11      186
12      119
13       77
14       85
15       59
16       62
17       29
18       36
19       29
20       28
Name: count, dtype: int64

In [ ]:
print("Clusters with >= 5 unique days:",
      (hotspot_stats["unique_days"] >= 5).sum())

print("Clusters with >= 10 unique days:",
      (hotspot_stats["unique_days"] >= 10).sum())

print("Clusters with >= 30 unique days:",
      (hotspot_stats["unique_days"] >= 30).sum())

print("Clusters with >= 100 unique days:",
      (hotspot_stats["unique_days"] >= 100).sum())

Clusters with >= 5 unique days: 6516
Clusters with >= 10 unique days: 1239
Clusters with >= 30 unique days: 188
Clusters with >= 100 unique days: 66

In [ ]:
hotspot_stats["active_duration_days"] = (
    hotspot_stats["last_detection"] -
    hotspot_stats["first_detection"]
).dt.days + 1

print(hotspot_stats["active_duration_days"].describe())

count    98584.000000
mean       146.844610
std        193.271512
min          1.000000
25%          1.000000
50%          4.000000
75%        357.000000
max        731.000000
Name: active_duration_days, dtype: float64

In [ ]:
persistent_candidates = hotspot_stats[
    hotspot_stats["unique_days"] >= 10
].copy()

print("Persistent candidates:", len(persistent_candidates))

print(
    persistent_candidates[
        ["total_detections",
         "unique_days",
         "active_duration_days",
         "mean_FRP",
         "max_FRP"]
    ].describe()
)

Persistent candidates: 1239
       total_detections  unique_days  active_duration_days     mean_FRP  \
count       1239.000000  1239.000000           1239.000000  1239.000000
mean          70.426150    27.950767            531.142050     5.090976
std          215.129602    49.213721            132.548656     2.897845
min           10.000000    10.000000             10.000000     0.438250
25%           21.000000    11.000000            395.000000     3.297143
50%           31.000000    14.000000            572.000000     4.978246
75%           54.500000    20.000000            610.500000     6.470544
max         4764.000000   578.000000            731.000000    21.904906

           max_FRP
count  1239.000000
mean     20.032050
std      19.985609
min       0.710000
25%       9.230000
50%      14.770000
75%      24.065000
max     265.430000

In [ ]:
clustered["ACQ_MONTH"] = clustered["ACQ_DATE"].dt.to_period("M")

monthly_stats = clustered.groupby("HOTSPOT_ID").agg(
    unique_months=("ACQ_MONTH", "nunique")
).reset_index()

hotspot_stats = hotspot_stats.merge(
    monthly_stats,
    on="HOTSPOT_ID",
    how="left"
)

print(hotspot_stats["unique_months"].describe())

count    98584.000000
mean         1.663495
std          1.108860
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         24.000000
Name: unique_months, dtype: float64

In [ ]:
print("\nCandidates by number of active months:")

print(
    hotspot_stats[
        hotspot_stats["unique_days"] >= 10
    ]["unique_months"]
    .value_counts()
    .sort_index()
)

Candidates by number of active months:
unique_months
1       1
2      29
3     139
4     281
5     237
6     183
7     108
8      70
9      29
10     19
11     15
12     12
13     11
14      5
15     10
16      8
17      4
18      3
19     13
20     12
21     18
22     12
23     10
24     10
Name: count, dtype: int64

In [ ]:
persistent_candidates = hotspot_stats[
    (hotspot_stats["unique_days"] >= 10) &
    (hotspot_stats["unique_months"] >= 6)
].copy()

print("Candidate persistent hotspots:", len(persistent_candidates))

Candidate persistent hotspots: 552

In [ ]:
hotspot_locations = clustered.groupby("HOTSPOT_ID").agg(
    hotspot_latitude=("LATITUDE", "mean"),
    hotspot_longitude=("LONGITUDE", "mean")
).reset_index()

persistent_candidates = persistent_candidates.merge(
    hotspot_locations,
    on="HOTSPOT_ID",
    how="left"
)

print(persistent_candidates[
    ["HOTSPOT_ID", "hotspot_latitude", "hotspot_longitude",
     "unique_days", "unique_months"]
].head(10))

   HOTSPOT_ID  hotspot_latitude  hotspot_longitude  unique_days  unique_months
0          26         27.080394          73.817179           70             21
1          27         26.876586          73.515424          269             21
2          28         24.821264          73.093785          282             24
3          29         24.690245          73.002674          183             21
4          30         23.408204          72.416596          106             20
5          32         23.315243          70.487057          228             23
6          33         23.304789          70.476777           33             13
7          34         23.313702          70.199973           81             15
8          35         23.263791          70.257548          221             23
9          36         23.118267          70.084872          135             22

In [ ]:
print("Persistent hotspots:", len(persistent_candidates))
print(
    "Missing coordinates:",
    persistent_candidates[
        ["hotspot_latitude", "hotspot_longitude"]
    ].isna().sum()
)

Persistent hotspots: 552
Missing coordinates: hotspot_latitude     0
hotspot_longitude    0
dtype: int64

In [ ]:
print("NORTH OSM:")
print(north_osm.columns.tolist())

print("\nWEST OSM:")
print(west_osm.columns.tolist())

In [ ]:
north_osm = pd.read_csv(north_file)
west_osm = pd.read_csv(west_file)

print("North OSM:", north_osm.shape)
print("West OSM:", west_osm.shape)

print("\nNorth columns:")
print(north_osm.columns.tolist())

print("\nWest columns:")
print(west_osm.columns.tolist())

/tmp/ipykernel_1661/3519531961.py:1: DtypeWarning: Columns (7,8,9,10,11,12,14,15,16,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  north_osm = pd.read_csv(north_file)

North OSM: (92549, 32)
West OSM: (32909, 9)

North columns:
['osm_id', 'osm_way_id', 'name', 'source_layer', 'feature_category', 'latitude', 'longitude', 'landuse', 'natural', 'man_made', 'building', 'craft', 'amenity', 'aeroway', 'railway', 'waterway', 'power', 'generator', 'generator_source', 'plant_source', 'plant_method', 'industrial', 'industrial_type', 'refinery', 'mine', 'quarry', 'fuel', 'pipeline', 'storage_tank', 'wetland', 'operator', 'other_tags']

West columns:
['osm_id', 'geometry_type', 'latitude', 'longitude', 'feature_type', 'matched_tags', 'name', 'node_count', 'geometry_wkt']

In [ ]:
print("========== NORTH OSM ==========")
print(north_osm["feature_category"].value_counts())

print("\n========== WEST OSM ==========")
print(west_osm["feature_type"].value_counts())

========== NORTH OSM ==========
feature_category
natural_context                44963
agriculture                    20785
transport_or_waterway          14349
industrial_area_or_facility     4005
industrial_building             2682
fuel_process_storage            2191
built_or_disturbed_context      1380
mining_quarry                   1300
water_utility                    712
power_energy                     145
craft_industry                    37
Name: count, dtype: int64

========== WEST OSM ==========
feature_type
power                        12158
industrial_building           7219
industrial                    6059
industrial_infrastructure     6052
extraction                    1421
Name: count, dtype: int64

In [ ]:
north_mask = (
    (persistent_candidates["hotspot_latitude"] >= NORTH_LAT_MIN) &
    (persistent_candidates["hotspot_latitude"] <= NORTH_LAT_MAX) &
    (persistent_candidates["hotspot_longitude"] >= NORTH_LON_MIN) &
    (persistent_candidates["hotspot_longitude"] <= NORTH_LON_MAX)
)

west_mask = (
    (persistent_candidates["hotspot_latitude"] >= WEST_LAT_MIN) &
    (persistent_candidates["hotspot_latitude"] <= WEST_LAT_MAX) &
    (persistent_candidates["hotspot_longitude"] >= WEST_LON_MIN) &
    (persistent_candidates["hotspot_longitude"] <= WEST_LON_MAX)
)

print("Hotspots in North:", north_mask.sum())
print("Hotspots in West:", west_mask.sum())
print("Hotspots in BOTH:", (north_mask & west_mask).sum())

Hotspots in North: 226
Hotspots in West: 358
Hotspots in BOTH: 32

In [ ]:
print("Total master rows:", len(firms_master))

duplicates = firms_master.duplicated(
    subset=[
        "LATITUDE",
        "LONGITUDE",
        "ACQ_DATE",
        "ACQ_TIME",
        "SATELLITE",
        "INSTRUMENT"
    ]
).sum()

print("Potential duplicate detections:", duplicates)

Total master rows: 604780
Potential duplicate detections: 52106

In [ ]:
# Check whether duplicates occur across NORTH and WEST
dup_check = (
    firms_master
    .groupby([
        "LATITUDE",
        "LONGITUDE",
        "ACQ_DATE",
        "ACQ_TIME",
        "SATELLITE",
        "INSTRUMENT"
    ])["REGION"]
    .nunique()
)

print("Detections appearing in BOTH regions:",
      (dup_check > 1).sum())

print("Detections appearing in only one region:",
      (dup_check == 1).sum())

Detections appearing in BOTH regions: 52106
Detections appearing in only one region: 500568

In [ ]:
# How many duplicated rows are specifically caused by North-West overlap?
cross_region_duplicates = firms_master.duplicated(
    subset=[
        "LATITUDE",
        "LONGITUDE",
        "ACQ_DATE",
        "ACQ_TIME",
        "SATELLITE",
        "INSTRUMENT"
    ],
    keep="first"
)

print(
    "Total duplicate rows:",
    cross_region_duplicates.sum()
)

Total duplicate rows: 52106

In [ ]:
# Remove duplicate FIRMS detections caused by North-West overlap

firms_clean = firms_master.drop_duplicates(
    subset=[
        "LATITUDE",
        "LONGITUDE",
        "ACQ_DATE",
        "ACQ_TIME",
        "SATELLITE",
        "INSTRUMENT"
    ]
).copy()

print("Original master:", len(firms_master))
print("Clean master:", len(firms_clean))
print("Removed duplicates:", len(firms_master) - len(firms_clean))

Original master: 604780
Clean master: 552674
Removed duplicates: 52106

In [ ]:
firms_clean.to_csv(
    "firms_study_regions_clean.csv",
    index=False
)

print("Saved: firms_study_regions_clean.csv")

Saved: firms_study_regions_clean.csv

In [ ]:
# Use the CLEAN FIRMS dataset for clustering

coords = firms_clean[["LATITUDE", "LONGITUDE"]].to_numpy()
coords_rad = np.radians(coords)

EARTH_RADIUS_M = 6_371_000
EPS_METERS = 500
EPS_RAD = EPS_METERS / EARTH_RADIUS_M

dbscan = DBSCAN(
    eps=EPS_RAD,
    min_samples=2,
    metric="haversine",
    algorithm="ball_tree",
    n_jobs=-1
)

labels_clean = dbscan.fit_predict(coords_rad)

firms_clean["HOTSPOT_ID"] = labels_clean

print("DBSCAN completed!")
print("Total clusters:",
      len(set(labels_clean)) - (1 if -1 in labels_clean else 0))

print("Noise points:",
      (labels_clean == -1).sum())

DBSCAN completed!
Total clusters: 85801
Noise points: 146326

In [ ]:
# Keep only actual DBSCAN clusters
clustered_clean = firms_clean[
    firms_clean["HOTSPOT_ID"] != -1
].copy()

# Make sure dates are datetime
clustered_clean["ACQ_DATE"] = pd.to_datetime(
    clustered_clean["ACQ_DATE"]
)

# Create month
clustered_clean["ACQ_MONTH"] = (
    clustered_clean["ACQ_DATE"].dt.to_period("M")
)

# Create hotspot statistics
hotspot_stats_clean = clustered_clean.groupby("HOTSPOT_ID").agg(
    total_detections=("HOTSPOT_ID", "size"),
    unique_days=("ACQ_DATE", "nunique"),
    unique_months=("ACQ_MONTH", "nunique"),
    first_detection=("ACQ_DATE", "min"),
    last_detection=("ACQ_DATE", "max"),
    mean_FRP=("FRP", "mean"),
    max_FRP=("FRP", "max")
).reset_index()

# Duration of activity
hotspot_stats_clean["active_duration_days"] = (
    hotspot_stats_clean["last_detection"]
    - hotspot_stats_clean["first_detection"]
).dt.days + 1

print("Total spatial clusters:",
      len(hotspot_stats_clean))

print("\nPersistence statistics:")
print(
    hotspot_stats_clean["unique_days"].describe()
)

Total spatial clusters: 85801

Persistence statistics:
count    85801.000000
mean         2.486498
std          6.801632
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max        578.000000
Name: unique_days, dtype: float64

In [ ]:
print("Clusters with >= 5 unique days:",
      (hotspot_stats_clean["unique_days"] >= 5).sum())

print("Clusters with >= 10 unique days:",
      (hotspot_stats_clean["unique_days"] >= 10).sum())

print("Clusters with >= 30 unique days:",
      (hotspot_stats_clean["unique_days"] >= 30).sum())

print("Clusters with >= 100 unique days:",
      (hotspot_stats_clean["unique_days"] >= 100).sum())

Clusters with >= 5 unique days: 6516
Clusters with >= 10 unique days: 1239
Clusters with >= 30 unique days: 188
Clusters with >= 100 unique days: 66

In [ ]:
persistent_candidates_clean = hotspot_stats_clean[
    (hotspot_stats_clean["unique_days"] >= 10) &
    (hotspot_stats_clean["unique_months"] >= 6)
].copy()

print("Persistent candidates:", len(persistent_candidates_clean))

print("\nUnique months distribution:")
print(
    persistent_candidates_clean["unique_months"]
    .value_counts()
    .sort_index()
)

Persistent candidates: 552

Unique months distribution:
unique_months
6     183
7     108
8      70
9      29
10     19
11     15
12     12
13     11
14      5
15     10
16      8
17      4
18      3
19     13
20     12
21     18
22     12
23     10
24     10
Name: count, dtype: int64

In [ ]:
# ==========================================
# STANDARDIZE NORTH OSM
# ==========================================

north_osm_std = north_osm[
    ["latitude", "longitude", "name", "feature_category"]
].copy()

north_osm_std["osm_category"] = north_osm_std["feature_category"].map({

    "industrial_area_or_facility": "industrial",
    "industrial_building": "industrial",
    "craft_industry": "industrial",

    "power_energy": "power",

    "mining_quarry": "mining",

    "fuel_process_storage": "fuel_storage",

    "agriculture": "agriculture",

    "transport_or_waterway": "transport",

    "water_utility": "water",

    "natural_context": "natural",

    "built_or_disturbed_context": "built",

}).fillna("other")

north_osm_std["source_region"] = "NORTH"


# ==========================================
# STANDARDIZE WEST OSM
# ==========================================

west_osm_std = west_osm[
    ["latitude", "longitude", "name", "feature_type"]
].copy()

west_osm_std["osm_category"] = west_osm_std["feature_type"].map({

    "industrial": "industrial",
    "industrial_building": "industrial",
    "industrial_infrastructure": "industrial",

    "power": "power",

    "extraction": "mining",

}).fillna("other")

west_osm_std["source_region"] = "WEST"


# ==========================================
# RENAME + COMBINE
# ==========================================

north_osm_std = north_osm_std[
    ["latitude", "longitude", "name",
     "osm_category", "source_region"]
]

west_osm_std = west_osm_std[
    ["latitude", "longitude", "name",
     "osm_category", "source_region"]
]

osm_master = pd.concat(
    [north_osm_std, west_osm_std],
    ignore_index=True
)


print("North OSM features:", len(north_osm_std))
print("West OSM features:", len(west_osm_std))
print("Total OSM features:", len(osm_master))

print("\nOSM categories:")
print(osm_master["osm_category"].value_counts())

North OSM features: 92549
West OSM features: 32909
Total OSM features: 125458

OSM categories:
osm_category
natural         44963
industrial      26054
agriculture     20785
transport       14349
power           12303
mining           2721
fuel_storage     2191
built            1380
water             712
Name: count, dtype: int64

In [ ]:
hotspots = persistent_candidates_clean[
    [
        "HOTSPOT_ID",
        "hotspot_latitude",
        "hotspot_longitude",
        "total_detections",
        "unique_days",
        "unique_months",
        "first_detection",
        "last_detection",
        "active_duration_days",
        "mean_FRP",
        "max_FRP"
    ]
].copy()

print("Hotspots:", len(hotspots))
print(hotspots.head())

KeyError: "['hotspot_latitude', 'hotspot_longitude'] not in index"

In [ ]:
# Get representative coordinates for each clean hotspot
hotspot_locations_clean = clustered_clean.groupby("HOTSPOT_ID").agg(
    hotspot_latitude=("LATITUDE", "mean"),
    hotspot_longitude=("LONGITUDE", "mean")
).reset_index()

# Add coordinates to the 552 persistent candidates
persistent_candidates_clean = persistent_candidates_clean.merge(
    hotspot_locations_clean,
    on="HOTSPOT_ID",
    how="left"
)

print("Persistent hotspots:", len(persistent_candidates_clean))

print(
    persistent_candidates_clean[
        [
            "HOTSPOT_ID",
            "hotspot_latitude",
            "hotspot_longitude",
            "unique_days",
            "unique_months"
        ]
    ].head()
)

Persistent hotspots: 552
   HOTSPOT_ID  hotspot_latitude  hotspot_longitude  unique_days  unique_months
0          26         27.080394          73.817179           70             21
1          27         26.876586          73.515424          269             21
2          28         24.821264          73.093785          282             24
3          29         24.690245          73.002674          183             21
4          30         23.408204          72.416596          106             20

In [ ]:
print(
    persistent_candidates_clean[
        ["hotspot_latitude", "hotspot_longitude"]
    ].isna().sum()
)

hotspot_latitude     0
hotspot_longitude    0
dtype: int64

In [ ]:
from sklearn.neighbors import BallTree
import numpy as np

# ------------------------------------------------
# Prepare hotspot coordinates
# ------------------------------------------------

hotspot_coords = np.radians(
    persistent_candidates_clean[
        ["hotspot_latitude", "hotspot_longitude"]
    ].to_numpy()
)

# ------------------------------------------------
# Earth radius
# ------------------------------------------------

EARTH_RADIUS_KM = 6371.0088

# ------------------------------------------------
# OSM coordinates
# ------------------------------------------------

osm_coords = np.radians(
    osm_master[
        ["latitude", "longitude"]
    ].to_numpy()
)

# Build spatial index
osm_tree = BallTree(
    osm_coords,
    metric="haversine"
)

print("OSM spatial index created!")
print("OSM features indexed:", len(osm_master))
print("Hotspots to match:", len(hotspot_coords))

OSM spatial index created!
OSM features indexed: 125458
Hotspots to match: 552

In [ ]:
distances, indices = osm_tree.query(
    hotspot_coords,
    k=1
)

nearest_distance_km = (
    distances[:, 0] * EARTH_RADIUS_KM
)

nearest_index = indices[:, 0]

print(nearest_distance_km[:10])

[5.9667152  0.82903584 0.46730879 0.09523375 0.5701743  0.16910735
 0.20635078 1.25324293 0.43323768 0.64793465]

In [ ]:
# Categories that matter for our classification
categories = [
    "industrial",
    "power",
    "mining",
    "fuel_storage",
    "agriculture",
    "transport"
]

# Create a copy of hotspot data
hotspot_osm = persistent_candidates_clean.copy()

for category in categories:

    # Select OSM features of this category
    osm_cat = osm_master[
        osm_master["osm_category"] == category
    ].copy()

    # If category doesn't exist, fill with NaN
    if len(osm_cat) == 0:
        hotspot_osm[f"distance_to_{category}_km"] = np.nan
        continue

    # Coordinates in radians
    osm_cat_coords = np.radians(
        osm_cat[["latitude", "longitude"]].to_numpy()
    )

    # Build category-specific BallTree
    tree = BallTree(
        osm_cat_coords,
        metric="haversine"
    )

    # Find nearest feature for every hotspot
    distances, indices = tree.query(
        hotspot_coords,
        k=1
    )

    # Convert radians → km
    distances_km = (
        distances[:, 0] * EARTH_RADIUS_KM
    )

    # Store distance
    hotspot_osm[
        f"distance_to_{category}_km"
    ] = distances_km

print("OSM distance features created!")

print(
    hotspot_osm[
        [
            "HOTSPOT_ID",
            "distance_to_industrial_km",
            "distance_to_power_km",
            "distance_to_mining_km",
            "distance_to_fuel_storage_km",
            "distance_to_agriculture_km",
            "distance_to_transport_km"
        ]
    ].head(10)
)

OSM distance features created!
   HOTSPOT_ID  distance_to_industrial_km  distance_to_power_km  \
0          26                  15.578091            319.739981
1          27                  12.644410            288.367904
2          28                   0.501288             59.769792
3          29                   0.095234             45.254906
4          30                   0.570174             12.259274
5          31                   0.169107              5.543293
6          32                   0.206351              4.351976
7          33                   4.431123             12.574271
8          34                   0.433238             12.506674
9          35                   0.647935              1.751156

   distance_to_mining_km  distance_to_fuel_storage_km  \
0              19.217704                    34.041174
1               0.829036                     4.538796
2               1.702899                     6.729748
3               1.585191                    12.064471
4              59.520224                   116.206757
5              20.084768                   211.404492
6              20.651400                   212.969854
7               1.253243                   231.260516
8               3.571421                   231.314071
9               6.826338                   255.188344

   distance_to_agriculture_km  distance_to_transport_km
0                   39.575294                 15.746427
1                   30.823322                 33.024747
2                    3.341023                  0.467309
3                    8.499625                  1.650086
4                  106.463072                100.749367
5                  193.959031                221.139018
6                  195.521549                222.697658
7                  213.402150                243.729536
8                  213.436947                242.605640
9                  237.282468                266.522546

In [ ]:
# Create proximity indicators

hotspot_osm["near_industrial_500m"] = (
    hotspot_osm["distance_to_industrial_km"] <= 0.5
).astype(int)

hotspot_osm["near_power_1km"] = (
    hotspot_osm["distance_to_power_km"] <= 1.0
).astype(int)

hotspot_osm["near_mining_5km"] = (
    hotspot_osm["distance_to_mining_km"] <= 5.0
).astype(int)

hotspot_osm["near_fuel_storage_2km"] = (
    hotspot_osm["distance_to_fuel_storage_km"] <= 2.0
).astype(int)

hotspot_osm["near_agriculture_1km"] = (
    hotspot_osm["distance_to_agriculture_km"] <= 1.0
).astype(int)

hotspot_osm["near_transport_1km"] = (
    hotspot_osm["distance_to_transport_km"] <= 1.0
).astype(int)

print(
    hotspot_osm[
        [
            "HOTSPOT_ID",
            "near_industrial_500m",
            "near_power_1km",
            "near_mining_5km",
            "near_fuel_storage_2km",
            "near_agriculture_1km",
            "near_transport_1km"
        ]
    ].head(10)
)

   HOTSPOT_ID  near_industrial_500m  near_power_1km  near_mining_5km  \
0          26                     0               0                0
1          27                     0               0                1
2          28                     0               0                1
3          29                     1               0                1
4          30                     0               0                0
5          31                     1               0                0
6          32                     1               0                0
7          33                     0               0                1
8          34                     1               0                1
9          35                     0               0                0

   near_fuel_storage_2km  near_agriculture_1km  near_transport_1km
0                      0                     0                   0
1                      0                     0                   0
2                      0                     0                   1
3                      0                     0                   0
4                      0                     0                   0
5                      0                     0                   0
6                      0                     0                   0
7                      0                     0                   0
8                      0                     0                   0
9                      0                     0                   0

In [ ]:
proximity_cols = [
    "near_industrial_500m",
    "near_power_1km",
    "near_mining_5km",
    "near_fuel_storage_2km",
    "near_agriculture_1km",
    "near_transport_1km"
]

print("========== OSM PROXIMITY COUNTS ==========\n")

for col in proximity_cols:
    count = hotspot_osm[col].sum()
    percentage = count / len(hotspot_osm) * 100

    print(
        f"{col:30s} : "
        f"{count:3d} / {len(hotspot_osm)} "
        f"({percentage:.1f}%)"
    )

========== OSM PROXIMITY COUNTS ==========

near_industrial_500m           :  77 / 552 (13.9%)
near_power_1km                 :  19 / 552 (3.4%)
near_mining_5km                :  76 / 552 (13.8%)
near_fuel_storage_2km          :   7 / 552 (1.3%)
near_agriculture_1km           :   7 / 552 (1.3%)
near_transport_1km             :  17 / 552 (3.1%)

In [ ]:
distance_cols = [
    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",
    "distance_to_transport_km"
]

print(hotspot_osm[distance_cols].describe().T)

                             count        mean         std       min  \
distance_to_industrial_km    552.0   67.542701   80.871396  0.003270
distance_to_power_km         552.0  124.785356  115.598271  0.048935
distance_to_mining_km        552.0   81.067599   78.783531  0.106898
distance_to_fuel_storage_km  552.0  413.220195  347.535919  0.497391
distance_to_agriculture_km   552.0  366.632028  313.757851  0.136556
distance_to_transport_km     552.0  344.681489  309.762634  0.069136

                                   25%         50%         75%          max
distance_to_industrial_km     2.453888   22.091406  111.480047   359.100167
distance_to_power_km         16.379959   93.618694  205.732168   418.198156
distance_to_mining_km        14.678163   58.485873  125.646433   382.618104
distance_to_fuel_storage_km  60.571414  340.832841  703.968942  1145.229464
distance_to_agriculture_km   42.632597  313.031577  623.602599  1035.445990
distance_to_transport_km     36.352802  277.346264  605.362016  1027.460220

In [ ]:
north_mask = (
    (persistent_candidates_clean["hotspot_latitude"] >= NORTH_LAT_MIN) &
    (persistent_candidates_clean["hotspot_latitude"] <= NORTH_LAT_MAX) &
    (persistent_candidates_clean["hotspot_longitude"] >= NORTH_LON_MIN) &
    (persistent_candidates_clean["hotspot_longitude"] <= NORTH_LON_MAX)
)

west_mask = (
    (persistent_candidates_clean["hotspot_latitude"] >= WEST_LAT_MIN) &
    (persistent_candidates_clean["hotspot_latitude"] <= WEST_LAT_MAX) &
    (persistent_candidates_clean["hotspot_longitude"] >= WEST_LON_MIN) &
    (persistent_candidates_clean["hotspot_longitude"] <= WEST_LON_MAX)
)

print("North only:", (north_mask & ~west_mask).sum())
print("West only:", (west_mask & ~north_mask).sum())
print("Overlap:", (north_mask & west_mask).sum())

North only: 194
West only: 326
Overlap: 32

In [ ]:
from sklearn.neighbors import BallTree
import numpy as np

# --------------------------------------------------
# 1. Create the three hotspot groups
# --------------------------------------------------

hotspots = persistent_candidates_clean.copy()

north_mask = (
    (hotspots["hotspot_latitude"] >= NORTH_LAT_MIN) &
    (hotspots["hotspot_latitude"] <= NORTH_LAT_MAX) &
    (hotspots["hotspot_longitude"] >= NORTH_LON_MIN) &
    (hotspots["hotspot_longitude"] <= NORTH_LON_MAX)
)

west_mask = (
    (hotspots["hotspot_latitude"] >= WEST_LAT_MIN) &
    (hotspots["hotspot_latitude"] <= WEST_LAT_MAX) &
    (hotspots["hotspot_longitude"] >= WEST_LON_MIN) &
    (hotspots["hotspot_longitude"] <= WEST_LON_MAX)
)

north_only = north_mask & ~west_mask
west_only = west_mask & ~north_mask
overlap = north_mask & west_mask

print("North only:", north_only.sum())
print("West only:", west_only.sum())
print("Overlap:", overlap.sum())
print("Total:", north_only.sum() + west_only.sum() + overlap.sum())


# --------------------------------------------------
# 2. Function to calculate nearest OSM distance
# --------------------------------------------------

EARTH_RADIUS_KM = 6371.0088

def nearest_category_distance(hotspot_df, osm_df, category):

    result = np.full(len(hotspot_df), np.nan)

    osm_cat = osm_df[
        osm_df["osm_category"] == category
    ]

    if len(hotspot_df) == 0 or len(osm_cat) == 0:
        return result

    hotspot_coords = np.radians(
        hotspot_df[
            ["hotspot_latitude", "hotspot_longitude"]
        ].to_numpy()
    )

    osm_coords = np.radians(
        osm_cat[
            ["latitude", "longitude"]
        ].to_numpy()
    )

    tree = BallTree(
        osm_coords,
        metric="haversine"
    )

    distances, _ = tree.query(
        hotspot_coords,
        k=1
    )

    result = distances[:, 0] * EARTH_RADIUS_KM

    return result


# --------------------------------------------------
# 3. Calculate distances using CORRECT OSM coverage
# --------------------------------------------------

osm_features = [
    "industrial",
    "power",
    "mining",
    "fuel_storage",
    "agriculture",
    "transport"
]

hotspot_osm_correct = hotspots.copy()

for category in osm_features:

    column = f"distance_to_{category}_km"

    # Start with everything unavailable
    hotspot_osm_correct[column] = np.nan

    # ----------------------------------------------
    # NORTH ONLY → North OSM
    # ----------------------------------------------

    north_hotspots = hotspots[north_only]

    hotspot_osm_correct.loc[
        north_only, column
    ] = nearest_category_distance(
        north_hotspots,
        north_osm_std,
        category
    )

    # ----------------------------------------------
    # WEST ONLY → West OSM
    # ----------------------------------------------

    west_hotspots = hotspots[west_only]

    hotspot_osm_correct.loc[
        west_only, column
    ] = nearest_category_distance(
        west_hotspots,
        west_osm_std,
        category
    )

    # ----------------------------------------------
    # OVERLAP → BOTH OSM datasets
    # ----------------------------------------------

    overlap_osm = pd.concat(
        [north_osm_std, west_osm_std],
        ignore_index=True
    )

    overlap_hotspots = hotspots[overlap]

    hotspot_osm_correct.loc[
        overlap, column
    ] = nearest_category_distance(
        overlap_hotspots,
        overlap_osm,
        category
    )


print("\nCorrected OSM distances created!")

distance_cols = [
    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",
    "distance_to_transport_km"
]

print(
    hotspot_osm_correct[distance_cols].describe().T
)

North only: 194
West only: 326
Overlap: 32
Total: 552

Corrected OSM distances created!
                             count        mean         std       min  \
distance_to_industrial_km    552.0   67.745255   81.353688  0.003270
distance_to_power_km         552.0  138.683716  139.329488  0.048935
distance_to_mining_km        552.0   81.363086   79.278488  0.106898
distance_to_fuel_storage_km  226.0   73.230881   78.430033  0.497391
distance_to_agriculture_km   226.0   61.764733   73.881562  0.136556
distance_to_transport_km     226.0   52.485039   67.511999  0.069136

                                   25%        50%         75%         max
distance_to_industrial_km     2.453888  22.091406  111.480047  359.100167
distance_to_power_km         16.379959  95.212289  222.778119  655.586410
distance_to_mining_km        14.678163  58.485873  125.646433  382.618104
distance_to_fuel_storage_km  17.229482  34.497572  113.370533  337.877181
distance_to_agriculture_km    6.492272  25.012991  106.441379  329.696525
distance_to_transport_km      5.394368  14.343575   95.417454  278.087494

In [ ]:
hotspot_osm_correct.to_csv(
    "persistent_hotspots_with_osm.csv",
    index=False
)

print("Saved:", len(hotspot_osm_correct), "hotspots")

Saved: 552 hotspots

In [ ]:
persistent = pd.read_csv("persistent_hotspots_with_osm.csv")
persistent.head()

,HOTSPOT_ID,total_detections,unique_days,unique_months,first_detection,last_detection,mean_FRP,max_FRP,active_duration_days,hotspot_latitude,hotspot_longitude,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,distance_to_transport_km
0,26,74,70,21,2024-01-01,2025-12-27,0.902973,4.03,727,27.080394,73.817179,15.578091,373.490365,19.217704,34.041174,39.575294,15.746427
1,27,514,269,21,2024-01-01,2025-12-27,1.131848,4.24,727,26.876586,73.515424,12.644410,410.451406,0.829036,4.538796,30.823322,33.024747
2,28,326,282,24,2024-01-01,2025-12-30,1.388344,5.13,730,24.821264,73.093785,0.501288,583.763570,1.702899,6.729748,3.341023,0.467309
3,29,208,183,21,2024-01-01,2025-12-27,1.407692,4.90,727,24.690245,73.002674,0.095234,600.653677,1.585191,12.064471,8.499625,1.650086
4,30,129,106,20,2024-01-01,2025-12-29,0.833721,2.93,729,23.408204,72.416596,0.570174,12.259274,59.520224,116.206757,106.463072,100.749367

In [ ]:
persistent.shape

(552, 17)

In [ ]:
import pandas as pd
import numpy as np

# ============================================
# 1. LOAD FILES
# ============================================

firms_file = "/content/drive/MyDrive/DataSetForpython/FIRMS_2024_2025_with_LandCover.csv"
hotspot_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm.csv"

firms = pd.read_csv(firms_file)
hotspots = pd.read_csv(hotspot_file)

print("FIRMS shape:", firms.shape)
print("Hotspots shape:", hotspots.shape)

# ============================================
# 2. CHECK LAND COVER
# ============================================

print("\nLand cover distribution:")
print(firms["LAND_COVER"].value_counts(dropna=False))

# ============================================
# 3. EXTRACT ONLY WHAT WE NEED
# ============================================

landcover = firms[
    ["LATITUDE", "LONGITUDE", "LAND_COVER"]
].copy()

landcover = landcover.dropna(subset=["LATITUDE", "LONGITUDE", "LAND_COVER"])

print("\nLand-cover data:")
print(landcover.head())

# ============================================
# 4. COUNT LAND-COVER TYPES AT EACH LOCATION
# ============================================

landcover_counts = (
    landcover
    .groupby(["LATITUDE", "LONGITUDE", "LAND_COVER"])
    .size()
    .reset_index(name="count")
)

# ============================================
# 5. FIND DOMINANT LAND COVER
# ============================================

dominant_landcover = (
    landcover_counts
    .sort_values(
        ["LATITUDE", "LONGITUDE", "count"],
        ascending=[True, True, False]
    )
    .drop_duplicates(["LATITUDE", "LONGITUDE"])
)

dominant_landcover = dominant_landcover[
    ["LATITUDE", "LONGITUDE", "LAND_COVER"]
].rename(columns={
    "LAND_COVER": "dominant_land_cover"
})

print("\nDominant land cover:")
print(dominant_landcover.head())

# ============================================
# 6. MERGE WITH 552 HOTSPOTS
# ============================================

# Make sure coordinate columns are numeric
hotspots["hotspot_latitude"] = pd.to_numeric(
    hotspots["hotspot_latitude"], errors="coerce"
)

hotspots["hotspot_longitude"] = pd.to_numeric(
    hotspots["hotspot_longitude"], errors="coerce"
)

dominant_landcover["LATITUDE"] = pd.to_numeric(
    dominant_landcover["LATITUDE"], errors="coerce"
)

dominant_landcover["LONGITUDE"] = pd.to_numeric(
    dominant_landcover["LONGITUDE"], errors="coerce"
)

# ============================================
# 7. IMPORTANT:
# Coordinates from FIRMS and hotspot representative
# coordinates may not be EXACTLY identical.
#
# Therefore, we will use nearest-neighbour matching.
# ============================================

from sklearn.neighbors import BallTree

# Convert degrees → radians
hotspot_coords = np.radians(
    hotspots[["hotspot_latitude", "hotspot_longitude"]].values
)

lc_coords = np.radians(
    dominant_landcover[["LATITUDE", "LONGITUDE"]].values
)

# BallTree using haversine distance
tree = BallTree(lc_coords, metric="haversine")

distances, indices = tree.query(
    hotspot_coords,
    k=1
)

# Convert radians to metres
distances_m = distances[:, 0] * 6371000

nearest_lc = dominant_landcover.iloc[
    indices[:, 0]
].reset_index(drop=True)

# ============================================
# 8. ADD LAND COVER TO HOTSPOTS
# ============================================

hotspots["dominant_land_cover"] = nearest_lc["dominant_land_cover"]

hotspots["land_cover_distance_m"] = distances_m

# ============================================
# 9. CHECK RESULT
# ============================================

print("\nFinal dataset shape:")
print(hotspots.shape)

print("\nLand-cover distribution among hotspots:")
print(hotspots["dominant_land_cover"].value_counts(dropna=False))

print("\nSample:")
display(
    hotspots[
        [
            "hotspot_latitude",
            "hotspot_longitude",
            "dominant_land_cover",
            "land_cover_distance_m"
        ]
    ].head(20)
)

# ============================================
# 10. SAVE FINAL FILE
# ============================================

output_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover.csv"

hotspots.to_csv(output_file, index=False)

print("\nSaved successfully:")
print(output_file)

FIRMS shape: (1198688, 16)
Hotspots shape: (552, 17)

Land cover distribution:
LAND_COVER
trees                 461300
crops                 403434
shrub_and_scrub       121724
bare                  116738
built                  60403
water                  28027
grass                   4689
flooded_vegetation      1204
snow_and_ice            1169
Name: count, dtype: int64

Land-cover data:
   LATITUDE  LONGITUDE LAND_COVER
0  18.74076   83.98029      crops
1  18.70938   83.45336      crops
2  18.70869   83.45004      grass
3  18.82113   83.86852      crops
4  18.77557   83.53876      trees

Dominant land cover:
   LATITUDE  LONGITUDE dominant_land_cover
0   8.07930   77.53805               water
1   8.08028   77.53823               built
2   8.08215   77.54140               built
3   8.09398   77.47668               built
4   8.09681   93.47365               grass

Final dataset shape:
(552, 19)

Land-cover distribution among hotspots:
dominant_land_cover
crops              256
built              112
bare                71
trees               48
shrub_and_scrub     44
water               21
Name: count, dtype: int64

Sample:

,hotspot_latitude,hotspot_longitude,dominant_land_cover,land_cover_distance_m
0,27.080394,73.817179,built,14.569299
1,26.876586,73.515424,bare,9.836285
2,24.821264,73.093785,built,8.423642
3,24.690245,73.002674,bare,5.457828
4,23.408204,72.416596,crops,7.683391
5,23.315243,70.487057,bare,11.726139
6,23.304789,70.476777,bare,7.112605
7,23.313702,70.199973,bare,9.857490
8,23.263791,70.257548,shrub_and_scrub,51.011826
9,23.118267,70.084872,built,37.547626
10,31.254769,76.926992,built,171.955619
11,27.668063,76.131131,built,25.870029
12,26.926807,73.468469,built,10.805330
13,26.605028,73.684174,built,1.602324
14,24.661397,74.633113,built,15.093864
15,23.415076,72.354899,crops,32.874718
16,23.170343,70.218120,bare,34.268812
17,23.105164,70.188032,built,24.994840
18,28.776973,76.946665,water,19.988501
19,28.648915,76.870304,crops,34.193177

Saved successfully:
/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover.csv

In [ ]:
!pip install -q earthengine-api geemap

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 29.5 MB/s eta 0:00:00

In [ ]:
import ee
import geemap

ee.Authenticate()
ee.Initialize()

EEException: ee.Initialize: no project found. Call with project= or see http://goo.gle/ee-auth.

In [ ]:
firms_file = "/content/drive/MyDrive/DataSetForpython/FIRMS_2024_2025_with_LandCover.csv"
hotspot_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm.csv"

firms = pd.read_csv(firms_file)
hotspots = pd.read_csv(hotspot_file)

print("FIRMS:", firms.shape)
print("Hotspots:", hotspots.shape)

print("\nLand cover values:")
print(firms["LAND_COVER"].value_counts(dropna=False))

FIRMS: (1198688, 16)
Hotspots: (552, 17)

Land cover values:
LAND_COVER
trees                 461300
crops                 403434
shrub_and_scrub       121724
bare                  116738
built                  60403
water                  28027
grass                   4689
flooded_vegetation      1204
snow_and_ice            1169
Name: count, dtype: int64

In [ ]:
firms_lc = firms[
    ["LATITUDE", "LONGITUDE", "LAND_COVER"]
].dropna()

hotspot_coords = hotspots[
    ["hotspot_latitude", "hotspot_longitude"]
].copy()

In [ ]:
from sklearn.neighbors import BallTree

# FIRMS coordinates
firms_coords = np.radians(
    firms_lc[["LATITUDE", "LONGITUDE"]].values
)

# Hotspot coordinates
hotspot_coords_rad = np.radians(
    hotspot_coords.values
)

# Build spatial tree
tree = BallTree(firms_coords, metric="haversine")

# 500 metres in radians
radius = 500 / 6371000

# Find FIRMS observations within 500 m
indices_array = tree.query_radius(
    hotspot_coords_rad,
    r=radius
)

print("Spatial matching completed.")

Spatial matching completed.

In [ ]:
dominant_landcovers = []
landcover_counts = []

for indices in indices_array:

    if len(indices) == 0:
        dominant_landcovers.append(np.nan)
        landcover_counts.append(0)
        continue

    lc_values = firms_lc.iloc[indices]["LAND_COVER"]

    counts = lc_values.value_counts()

    dominant_landcovers.append(counts.index[0])
    landcover_counts.append(len(lc_values))

In [ ]:
hotspots["dominant_land_cover"] = dominant_landcovers
hotspots["land_cover_observations"] = landcover_counts

In [ ]:
print(
    hotspots[
        [
            "hotspot_latitude",
            "hotspot_longitude",
            "dominant_land_cover",
            "land_cover_observations"
        ]
    ].head(20)
)

    hotspot_latitude  hotspot_longitude dominant_land_cover  \
0          27.080394          73.817179                bare
1          26.876586          73.515424                bare
2          24.821264          73.093785               built
3          24.690245          73.002674                bare
4          23.408204          72.416596               crops
5          23.315243          70.487057                bare
6          23.304789          70.476777                bare
7          23.313702          70.199973                bare
8          23.263791          70.257548               built
9          23.118267          70.084872               built
10         31.254769          76.926992               built
11         27.668063          76.131131               built
12         26.926807          73.468469               built
13         26.605028          73.684174               built
14         24.661397          74.633113                bare
15         23.415076          72.354899               crops
16         23.170343          70.218120                bare
17         23.105164          70.188032                bare
18         28.776973          76.946665               crops
19         28.648915          76.870304               crops

    land_cover_observations
0                        74
1                       469
2                       326
3                       208
4                       128
5                       247
6                        32
7                        83
8                       193
9                       121
10                       89
11                      313
12                       94
13                      142
14                      541
15                       99
16                       20
17                      100
18                       44
19                       12

In [ ]:
landcover_classes = [
    "water",
    "trees",
    "grass",
    "flooded_vegetation",
    "crops",
    "shrub_and_scrub",
    "built",
    "bare",
    "snow_and_ice"
]

for lc in landcover_classes:

    hotspots[f"lc_{lc}_ratio"] = 0.0

In [ ]:
for i, indices in enumerate(indices_array):

    if len(indices) == 0:
        continue

    values = firms_lc.iloc[indices]["LAND_COVER"]

    proportions = values.value_counts(normalize=True)

    for lc, proportion in proportions.items():

        if lc in landcover_classes:
            hotspots.loc[i, f"lc_{lc}_ratio"] = proportion

In [ ]:
output_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover(1).csv"

hotspots.to_csv(output_file, index=False)

print("Saved:", output_file)
print("Final rows:", len(hotspots))

Saved: /content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover(1).csv
Final rows: 552

In [ ]:
output_file = pd.read_csv("/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover(1).csv")
output_file.head()

,HOTSPOT_ID,total_detections,unique_days,unique_months,first_detection,last_detection,mean_FRP,max_FRP,active_duration_days,hotspot_latitude,...,land_cover_observations,lc_water_ratio,lc_trees_ratio,lc_grass_ratio,lc_flooded_vegetation_ratio,lc_crops_ratio,lc_shrub_and_scrub_ratio,lc_built_ratio,lc_bare_ratio,lc_snow_and_ice_ratio
0,26,74,70,21,2024-01-01,2025-12-27,0.902973,4.03,727,27.080394,...,74,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.418919,0.581081,0.0
1,27,514,269,21,2024-01-01,2025-12-27,1.131848,4.24,727,26.876586,...,469,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.287846,0.712154,0.0
2,28,326,282,24,2024-01-01,2025-12-30,1.388344,5.13,730,24.821264,...,326,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.733129,0.266871,0.0
3,29,208,183,21,2024-01-01,2025-12-27,1.407692,4.90,727,24.690245,...,208,0.0,0.000000,0.0,0.0,0.000000,0.024038,0.451923,0.524038,0.0
4,30,129,106,20,2024-01-01,2025-12-29,0.833721,2.93,729,23.408204,...,128,0.0,0.007812,0.0,0.0,0.789062,0.000000,0.203125,0.000000,0.0

In [ ]:
print(hotspots["dominant_land_cover"].value_counts(dropna=False))
print(hotspots["land_cover_observations"].describe())

dominant_land_cover
crops              267
built              113
bare                67
trees               55
shrub_and_scrub     31
water               17
NaN                  2
Name: count, dtype: int64
count     552.000000
mean       44.646739
std       102.074811
min         0.000000
25%         5.000000
50%         8.000000
75%        30.000000
max      1344.000000
Name: land_cover_observations, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

# 552-hotspot master file
hotspot_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover(1).csv"

# FIRMS + weather file
weather_file = "/content/drive/MyDrive/DataSetForpython/FIRMS_Weather_2024_2025.csv"

hotspots = pd.read_csv(hotspot_file)
weather = pd.read_csv(weather_file)

print("Hotspots:", hotspots.shape)
print("Weather FIRMS:", weather.shape)

print(hotspots.columns.tolist())
print(weather.columns.tolist())

Hotspots: (552, 28)
Weather FIRMS: (1198688, 10)
['HOTSPOT_ID', 'total_detections', 'unique_days', 'unique_months', 'first_detection', 'last_detection', 'mean_FRP', 'max_FRP', 'active_duration_days', 'hotspot_latitude', 'hotspot_longitude', 'distance_to_industrial_km', 'distance_to_power_km', 'distance_to_mining_km', 'distance_to_fuel_storage_km', 'distance_to_agriculture_km', 'distance_to_transport_km', 'dominant_land_cover', 'land_cover_observations', 'lc_water_ratio', 'lc_trees_ratio', 'lc_grass_ratio', 'lc_flooded_vegetation_ratio', 'lc_crops_ratio', 'lc_shrub_and_scrub_ratio', 'lc_built_ratio', 'lc_bare_ratio', 'lc_snow_and_ice_ratio']
['LATITUDE', 'LONGITUDE', 'ACQ_DATE', 'ACQ_TIME', 'T2M_C', 'D2M_C', 'U10_MS', 'V10_MS', 'TP', 'SSRD']

In [ ]:
hotspots["first_detection"] = pd.to_datetime(
    hotspots["first_detection"]
)

hotspots["last_detection"] = pd.to_datetime(
    hotspots["last_detection"]
)

weather["ACQ_DATE"] = pd.to_datetime(
    weather["ACQ_DATE"]
)

In [ ]:
weather["WIND_SPEED_MS"] = np.sqrt(
    weather["U10_MS"]**2 +
    weather["V10_MS"]**2
)

In [ ]:
from sklearn.neighbors import BallTree

# Remove rows with missing coordinates
weather_clean = weather.dropna(
    subset=["LATITUDE", "LONGITUDE"]
).copy()

# Coordinates in radians
weather_coords = np.radians(
    weather_clean[["LATITUDE", "LONGITUDE"]].values
)

hotspot_coords = np.radians(
    hotspots[
        ["hotspot_latitude", "hotspot_longitude"]
    ].values
)

# Build spatial tree
tree = BallTree(
    weather_coords,
    metric="haversine"
)

# 500 metres
radius = 500 / 6371000

indices_array = tree.query_radius(
    hotspot_coords,
    r=radius
)

print("Spatial matching completed.")

Spatial matching completed.

In [ ]:
weather_features = []

for i, indices in enumerate(indices_array):

    if len(indices) == 0:

        weather_features.append({
            "HOTSPOT_ID": hotspots.iloc[i]["HOTSPOT_ID"],
            "mean_temperature": np.nan,
            "max_temperature": np.nan,
            "min_temperature": np.nan,
            "mean_wind_speed": np.nan,
            "max_wind_speed": np.nan,
            "mean_dewpoint": np.nan,
            "mean_precipitation": np.nan,
            "total_precipitation": np.nan,
            "mean_solar_radiation": np.nan,
            "weather_observations": 0
        })

        continue

    w = weather_clean.iloc[indices]

    weather_features.append({

        "HOTSPOT_ID":
            hotspots.iloc[i]["HOTSPOT_ID"],

        "mean_temperature":
            w["T2M_C"].mean(),

        "max_temperature":
            w["T2M_C"].max(),

        "min_temperature":
            w["T2M_C"].min(),

        "mean_wind_speed":
            w["WIND_SPEED_MS"].mean(),

        "max_wind_speed":
            w["WIND_SPEED_MS"].max(),

        "mean_dewpoint":
            w["D2M_C"].mean(),

        "mean_precipitation":
            w["TP"].mean(),

        "total_precipitation":
            w["TP"].sum(),

        "mean_solar_radiation":
            w["SSRD"].mean(),

        "weather_observations":
            len(w)
    })

weather_features = pd.DataFrame(weather_features)

print(weather_features.shape)

display(weather_features.head())

(552, 11)

,HOTSPOT_ID,mean_temperature,max_temperature,min_temperature,mean_wind_speed,max_wind_speed,mean_dewpoint,mean_precipitation,total_precipitation,mean_solar_radiation,weather_observations
0,26,18.365911,33.192047,8.120392,2.659297,5.639303,9.234643,0.000198,0.014620,1.910770e+07,74
1,27,18.036905,34.357086,7.941071,2.854856,6.404039,7.440394,0.000063,0.029516,1.908665e+07,469
2,28,18.099106,30.347321,7.735565,1.633095,2.689445,8.746572,0.000219,0.071381,1.999375e+07,326
3,29,20.142580,31.974274,9.710022,1.383084,2.604256,10.483322,0.000278,0.057880,1.986809e+07,208
4,30,20.797448,36.718658,12.216095,2.708787,5.013118,11.186905,0.000154,0.019713,1.979136e+07,128

In [ ]:
final_dataset = hotspots.merge(
    weather_features,
    on="HOTSPOT_ID",
    how="left"
)

print("Final shape:", final_dataset.shape)

Final shape: (552, 38)

In [ ]:
weather_columns = [
    "mean_temperature",
    "max_temperature",
    "min_temperature",
    "mean_wind_speed",
    "max_wind_speed",
    "mean_dewpoint",
    "mean_precipitation",
    "total_precipitation",
    "mean_solar_radiation",
    "weather_observations"
]

display(
    final_dataset[
        ["HOTSPOT_ID"] + weather_columns
    ].head(20)
)

,HOTSPOT_ID,mean_temperature,max_temperature,min_temperature,mean_wind_speed,max_wind_speed,mean_dewpoint,mean_precipitation,total_precipitation,mean_solar_radiation,weather_observations
0,26,18.365911,33.192047,8.120392,2.659297,5.639303,9.234643,1.975633e-04,0.014620,1.910770e+07,74
1,27,18.036905,34.357086,7.941071,2.854856,6.404039,7.440394,6.293493e-05,0.029516,1.908665e+07,469
2,28,18.099106,30.347321,7.735565,1.633095,2.689445,8.746572,2.189601e-04,0.071381,1.999375e+07,326
3,29,20.142580,31.974274,9.710022,1.383084,2.604256,10.483322,2.782702e-04,0.057880,1.986809e+07,208
4,30,20.797448,36.718658,12.216095,2.708787,5.013118,11.186905,1.540085e-04,0.019713,1.979136e+07,128
5,31,21.863893,32.530365,13.447052,3.496152,6.523030,13.101916,1.805295e-04,0.044591,2.017063e+07,247
6,32,19.031130,28.364868,13.447052,3.383095,5.961296,11.226885,7.844076e-07,0.000025,1.919919e+07,32
7,33,18.367771,29.674957,13.563751,3.221798,5.710706,9.594738,1.244492e-06,0.000103,1.838519e+07,83
8,34,21.436136,30.337494,13.661407,3.402689,7.214533,13.403366,9.651358e-05,0.018627,1.912954e+07,193
9,35,23.712987,37.687164,13.912384,4.501831,10.088430,14.188199,4.895954e-05,0.005924,1.946243e+07,121
10,71,12.944823,23.352692,2.534363,1.723462,2.803945,9.666399,7.269491e-04,0.064698,1.974299e+07,89
11,75,18.171262,32.353180,6.726349,2.210983,5.055410,11.084991,3.812386e-04,0.119328,1.858942e+07,313
12,76,18.034412,32.468658,8.883789,2.894546,5.157003,7.871006,5.123732e-05,0.004816,1.874965e+07,94
13,77,18.039781,31.763580,9.333099,2.650100,5.509100,9.001216,8.960076e-05,0.012723,1.849871e+07,142
14,78,18.146174,32.184540,8.096191,2.121398,4.649773,9.249556,1.459189e-04,0.078942,1.980645e+07,541
15,79,22.025544,33.052399,14.082184,2.643906,4.250901,11.881958,2.353915e-05,0.002330,2.094526e+07,99
16,80,18.271159,24.791229,13.560822,3.797579,4.900935,7.972441,9.234420e-07,0.000018,1.983897e+07,20
17,81,21.896625,36.730286,13.779083,3.953007,6.798969,12.703953,2.634531e-05,0.002635,2.069433e+07,100
18,132,15.233785,31.686920,6.976349,2.589431,4.969196,9.496763,1.772265e-04,0.007798,1.864760e+07,44
19,133,18.601448,31.676880,8.219147,2.230040,3.032576,12.175219,7.672359e-06,0.000092,1.851592e+07,12

In [ ]:
print(
    final_dataset[weather_columns].describe()
)

       mean_temperature  max_temperature  min_temperature  mean_wind_speed  \
count        550.000000       550.000000       550.000000       550.000000
mean          27.172843        34.378290        21.251821         2.297001
std            6.025035         5.329741         7.624915         0.769976
min           11.434338        17.462921         1.102905         0.646051
25%           22.132939        30.169891        15.211601         1.782604
50%           27.261973        35.069122        22.685501         2.216008
75%           31.740045        38.672028        26.490685         2.649671
max           42.397858        45.963776        42.271881         6.188340

       max_wind_speed  mean_dewpoint  mean_precipitation  total_precipitation  \
count      550.000000     550.000000        5.500000e+02           550.000000
mean         3.706281      12.078037        1.338922e-04             0.012494
std          1.501231       3.805409        2.393929e-04             0.038371
min          0.646051      -8.246063        0.000000e+00             0.000000
25%          2.668269       9.717938        3.113677e-07             0.000002
50%          3.416716      12.403198        1.018442e-05             0.000094
75%          4.427453      14.425513        1.768785e-04             0.006073
max         11.641480      22.104765        1.479511e-03             0.531427

       mean_solar_radiation  weather_observations
count          5.500000e+02            552.000000
mean           1.678112e+07             44.646739
std            3.695175e+06            102.074811
min            8.035804e+06              0.000000
25%            1.358551e+07              5.000000
50%            1.741242e+07              8.000000
75%            1.978977e+07             30.000000
max            2.813860e+07           1344.000000

In [ ]:
print(
    final_dataset[weather_columns].isna().sum()
)

mean_temperature        2
max_temperature         2
min_temperature         2
mean_wind_speed         2
max_wind_speed          2
mean_dewpoint           2
mean_precipitation      2
total_precipitation     2
mean_solar_radiation    2
weather_observations    0
dtype: int64

In [ ]:
output_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_final_features.csv"

final_dataset.to_csv(
    output_file,
    index=False
)

print("Saved successfully!")
print(output_file)
print("Rows:", len(final_dataset))
print("Columns:", len(final_dataset.columns))

Saved successfully!
/content/drive/MyDrive/DataSetForpython/persistent_hotspots_final_features.csv
Rows: 552
Columns: 38

In [ ]:
final_data = pd.read_csv("/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover.csv")

In [ ]:
final_data.head()

,HOTSPOT_ID,total_detections,unique_days,unique_months,first_detection,last_detection,mean_FRP,max_FRP,active_duration_days,hotspot_latitude,...,land_cover_observations,lc_water_ratio,lc_trees_ratio,lc_grass_ratio,lc_flooded_vegetation_ratio,lc_crops_ratio,lc_shrub_and_scrub_ratio,lc_built_ratio,lc_bare_ratio,lc_snow_and_ice_ratio
0,26,74,70,21,2024-01-01,2025-12-27,0.902973,4.03,727,27.080394,...,74,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.418919,0.581081,0.0
1,27,514,269,21,2024-01-01,2025-12-27,1.131848,4.24,727,26.876586,...,469,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.287846,0.712154,0.0
2,28,326,282,24,2024-01-01,2025-12-30,1.388344,5.13,730,24.821264,...,326,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.733129,0.266871,0.0
3,29,208,183,21,2024-01-01,2025-12-27,1.407692,4.90,727,24.690245,...,208,0.0,0.000000,0.0,0.0,0.000000,0.024038,0.451923,0.524038,0.0
4,30,129,106,20,2024-01-01,2025-12-29,0.833721,2.93,729,23.408204,...,128,0.0,0.007812,0.0,0.0,0.789062,0.000000,0.203125,0.000000,0.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

# =========================================================
# 1. LOAD FILES
# =========================================================

hotspot_file = "/content/drive/MyDrive/DataSetForpython/persistent_hotspots_with_osm_landcover(1).csv"
weather_file = "/content/drive/MyDrive/DataSetForpython/FIRMS_Weather_2024_2025.csv"

hotspots = pd.read_csv(hotspot_file)
weather = pd.read_csv(weather_file)

print("Hotspots:", hotspots.shape)
print("Weather FIRMS:", weather.shape)

Hotspots: (552, 28)
Weather FIRMS: (1198688, 10)

In [ ]:
# Convert date
weather["ACQ_DATE"] = pd.to_datetime(weather["ACQ_DATE"])

# Calculate wind speed
weather["WIND_SPEED_MS"] = np.sqrt(
    weather["U10_MS"]**2 +
    weather["V10_MS"]**2
)

# Remove observations without coordinates
weather = weather.dropna(
    subset=["LATITUDE", "LONGITUDE"]
).reset_index(drop=True)

print("Weather rows after cleaning:", len(weather))

Weather rows after cleaning: 1198688

In [ ]:
# Hotspot coordinates
hotspot_coords = np.radians(
    hotspots[
        ["hotspot_latitude", "hotspot_longitude"]
    ].values
)

# Weather/FIRMS coordinates
weather_coords = np.radians(
    weather[
        ["LATITUDE", "LONGITUDE"]
    ].values
)

# Build spatial index
tree = BallTree(
    hotspot_coords,
    metric="haversine"
)

# Find nearest hotspot for every FIRMS-weather observation
distances, indices = tree.query(
    weather_coords,
    k=1
)

# Convert radians → metres
distances_m = distances[:, 0] * 6371000

weather["HOTSPOT_INDEX"] = indices[:, 0]
weather["HOTSPOT_DISTANCE_M"] = distances_m

print(weather[[
    "LATITUDE",
    "LONGITUDE",
    "HOTSPOT_INDEX",
    "HOTSPOT_DISTANCE_M"
]].head())

   LATITUDE  LONGITUDE  HOTSPOT_INDEX  HOTSPOT_DISTANCE_M
0  18.74076   83.98029            413       374385.816109
1  18.70938   83.45336            413       318888.257597
2  18.70869   83.45004            413       318538.728361
3  18.82113   83.86852            413       362780.525412
4  18.77557   83.53876            413       327950.175923

In [ ]:
weather_matched = weather[
    weather["HOTSPOT_DISTANCE_M"] <= 500
].copy()

print("Matched observations:", len(weather_matched))
print("Unique hotspots matched:",
      weather_matched["HOTSPOT_INDEX"].nunique())

Matched observations: 24645
Unique hotspots matched: 550

In [ ]:
weather_summary = (
    weather_matched
    .groupby("HOTSPOT_INDEX")
    .agg(
        mean_temperature=("T2M_C", "mean"),
        max_temperature=("T2M_C", "max"),
        min_temperature=("T2M_C", "min"),

        mean_wind_speed=("WIND_SPEED_MS", "mean"),
        max_wind_speed=("WIND_SPEED_MS", "max"),

        mean_dewpoint=("D2M_C", "mean"),

        mean_precipitation=("TP", "mean"),
        total_precipitation=("TP", "sum"),

        mean_solar_radiation=("SSRD", "mean"),

        weather_observations=("T2M_C", "count")
    )
    .reset_index()
)

print(weather_summary.shape)
display(weather_summary.head())

(550, 11)

,HOTSPOT_INDEX,mean_temperature,max_temperature,min_temperature,mean_wind_speed,max_wind_speed,mean_dewpoint,mean_precipitation,total_precipitation,mean_solar_radiation,weather_observations
0,0,18.365911,33.192047,8.120392,2.659297,5.639303,9.234643,0.000198,0.014620,1.910770e+07,74
1,1,18.036905,34.357086,7.941071,2.854856,6.404039,7.440394,0.000063,0.029516,1.908665e+07,469
2,2,18.099106,30.347321,7.735565,1.633095,2.689445,8.746572,0.000219,0.071381,1.999375e+07,326
3,3,20.142580,31.974274,9.710022,1.383084,2.604256,10.483322,0.000278,0.057880,1.986809e+07,208
4,4,20.797448,36.718658,12.216095,2.708787,5.013118,11.186905,0.000154,0.019713,1.979136e+07,128

In [ ]:
final_dataset = hotspots.copy()

final_dataset = final_dataset.merge(
    weather_summary,
    left_index=True,
    right_on="HOTSPOT_INDEX",
    how="left"
)

# Remove helper column
final_dataset = final_dataset.drop(
    columns=["HOTSPOT_INDEX"]
)

print("Final dataset shape:", final_dataset.shape)

Final dataset shape: (552, 38)

In [ ]:
weather_columns = [
    "mean_temperature",
    "max_temperature",
    "min_temperature",
    "mean_wind_speed",
    "max_wind_speed",
    "mean_dewpoint",
    "mean_precipitation",
    "total_precipitation",
    "mean_solar_radiation",
    "weather_observations"
]

display(
    final_dataset[
        ["HOTSPOT_ID"] + weather_columns
    ].head(20)
)

,HOTSPOT_ID,mean_temperature,max_temperature,min_temperature,mean_wind_speed,max_wind_speed,mean_dewpoint,mean_precipitation,total_precipitation,mean_solar_radiation,weather_observations
0.0,26,18.365911,33.192047,8.120392,2.659297,5.639303,9.234643,1.975633e-04,0.014620,1.910770e+07,74.0
1.0,27,18.036905,34.357086,7.941071,2.854856,6.404039,7.440394,6.293493e-05,0.029516,1.908665e+07,469.0
2.0,28,18.099106,30.347321,7.735565,1.633095,2.689445,8.746572,2.189601e-04,0.071381,1.999375e+07,326.0
3.0,29,20.142580,31.974274,9.710022,1.383084,2.604256,10.483322,2.782702e-04,0.057880,1.986809e+07,208.0
4.0,30,20.797448,36.718658,12.216095,2.708787,5.013118,11.186905,1.540085e-04,0.019713,1.979136e+07,128.0
5.0,31,21.863893,32.530365,13.447052,3.496152,6.523030,13.101916,1.805295e-04,0.044591,2.017063e+07,247.0
6.0,32,19.031130,28.364868,13.447052,3.383095,5.961296,11.226885,7.844076e-07,0.000025,1.919919e+07,32.0
7.0,33,18.367771,29.674957,13.563751,3.221798,5.710706,9.594738,1.244492e-06,0.000103,1.838519e+07,83.0
8.0,34,21.436136,30.337494,13.661407,3.402689,7.214533,13.403366,9.651358e-05,0.018627,1.912954e+07,193.0
9.0,35,23.712987,37.687164,13.912384,4.501831,10.088430,14.188199,4.895954e-05,0.005924,1.946243e+07,121.0
10.0,71,12.944823,23.352692,2.534363,1.723462,2.803945,9.666399,7.269491e-04,0.064698,1.974299e+07,89.0
11.0,75,18.171262,32.353180,6.726349,2.210983,5.055410,11.084991,3.812386e-04,0.119328,1.858942e+07,313.0
12.0,76,18.034412,32.468658,8.883789,2.894546,5.157003,7.871006,5.123732e-05,0.004816,1.874965e+07,94.0
13.0,77,18.039781,31.763580,9.333099,2.650100,5.509100,9.001216,8.960076e-05,0.012723,1.849871e+07,142.0
14.0,78,18.146174,32.184540,8.096191,2.121398,4.649773,9.249556,1.459189e-04,0.078942,1.980645e+07,541.0
15.0,79,22.025544,33.052399,14.082184,2.643906,4.250901,11.881958,2.353915e-05,0.002330,2.094526e+07,99.0
16.0,80,18.271159,24.791229,13.560822,3.797579,4.900935,7.972441,9.234420e-07,0.000018,1.983897e+07,20.0
17.0,81,21.896625,36.730286,13.779083,3.953007,6.798969,12.703953,2.634531e-05,0.002635,2.069433e+07,100.0
18.0,132,15.233785,31.686920,6.976349,2.589431,4.969196,9.496763,1.772265e-04,0.007798,1.864760e+07,44.0
19.0,133,18.601448,31.676880,8.219147,2.230040,3.032576,12.175219,7.672359e-06,0.000092,1.851592e+07,12.0

In [ ]:
print(final_dataset[weather_columns].describe())

       mean_temperature  max_temperature  min_temperature  mean_wind_speed  \
count        550.000000       550.000000       550.000000       550.000000
mean          27.172843        34.378290        21.251821         2.297001
std            6.025035         5.329741         7.624915         0.769976
min           11.434338        17.462921         1.102905         0.646051
25%           22.132939        30.169891        15.211601         1.782604
50%           27.261973        35.069122        22.685501         2.216008
75%           31.740045        38.672028        26.490685         2.649671
max           42.397858        45.963776        42.271881         6.188340

       max_wind_speed  mean_dewpoint  mean_precipitation  total_precipitation  \
count      550.000000     550.000000        5.500000e+02           550.000000
mean         3.706281      12.078037        1.338922e-04             0.012494
std          1.501231       3.805409        2.393929e-04             0.038371
min          0.646051      -8.246063        0.000000e+00             0.000000
25%          2.668269       9.717938        3.113677e-07             0.000002
50%          3.416716      12.403198        1.018442e-05             0.000094
75%          4.427453      14.425513        1.768785e-04             0.006073
max         11.641480      22.104765        1.479511e-03             0.531427

       mean_solar_radiation  weather_observations
count          5.500000e+02            550.000000
mean           1.678112e+07             44.809091
std            3.695175e+06            102.224929
min            8.035804e+06              1.000000
25%            1.358551e+07              5.000000
50%            1.741242e+07              8.000000
75%            1.978977e+07             30.000000
max            2.813860e+07           1344.000000

In [ ]:
print(
    final_dataset[weather_columns].isna().sum()
)

mean_temperature        2
max_temperature         2
min_temperature         2
mean_wind_speed         2
max_wind_speed          2
mean_dewpoint           2
mean_precipitation      2
total_precipitation     2
mean_solar_radiation    2
weather_observations    2
dtype: int64

In [ ]:
output_file = "/content/drive/MyDrive/DataSetForpython/weather.csv"

final_dataset.to_csv(
    output_file,
    index=False
)

print("Saved successfully!")
print(output_file)
print("Rows:", len(final_dataset))

Saved successfully!
/content/drive/MyDrive/DataSetForpython/weather.csv
Rows: 552

In [ ]:
print(final_dataset.shape)

print("\nMissing values:")
print(final_dataset.isna().sum())

print("\nWeather summary:")
print(final_dataset[[
    "mean_temperature",
    "max_temperature",
    "min_temperature",
    "mean_wind_speed",
    "max_wind_speed",
    "mean_dewpoint",
    "mean_precipitation",
    "total_precipitation",
    "mean_solar_radiation",
    "weather_observations"
]].describe())

(552, 38)

Missing values:
HOTSPOT_ID                       0
total_detections                 0
unique_days                      0
unique_months                    0
first_detection                  0
last_detection                   0
mean_FRP                         0
max_FRP                          0
active_duration_days             0
hotspot_latitude                 0
hotspot_longitude                0
distance_to_industrial_km        0
distance_to_power_km             0
distance_to_mining_km            0
distance_to_fuel_storage_km    326
distance_to_agriculture_km     326
distance_to_transport_km       326
dominant_land_cover              2
land_cover_observations          0
lc_water_ratio                   0
lc_trees_ratio                   0
lc_grass_ratio                   0
lc_flooded_vegetation_ratio      0
lc_crops_ratio                   0
lc_shrub_and_scrub_ratio         0
lc_built_ratio                   0
lc_bare_ratio                    0
lc_snow_and_ice_ratio            0
mean_temperature                 2
max_temperature                  2
min_temperature                  2
mean_wind_speed                  2
max_wind_speed                   2
mean_dewpoint                    2
mean_precipitation               2
total_precipitation              2
mean_solar_radiation             2
weather_observations             2
dtype: int64

Weather summary:
       mean_temperature  max_temperature  min_temperature  mean_wind_speed  \
count        550.000000       550.000000       550.000000       550.000000
mean          27.172843        34.378290        21.251821         2.297001
std            6.025035         5.329741         7.624915         0.769976
min           11.434338        17.462921         1.102905         0.646051
25%           22.132939        30.169891        15.211601         1.782604
50%           27.261973        35.069122        22.685501         2.216008
75%           31.740045        38.672028        26.490685         2.649671
max           42.397858        45.963776        42.271881         6.188340

       max_wind_speed  mean_dewpoint  mean_precipitation  total_precipitation  \
count      550.000000     550.000000        5.500000e+02           550.000000
mean         3.706281      12.078037        1.338922e-04             0.012494
std          1.501231       3.805409        2.393929e-04             0.038371
min          0.646051      -8.246063        0.000000e+00             0.000000
25%          2.668269       9.717938        3.113677e-07             0.000002
50%          3.416716      12.403198        1.018442e-05             0.000094
75%          4.427453      14.425513        1.768785e-04             0.006073
max         11.641480      22.104765        1.479511e-03             0.531427

       mean_solar_radiation  weather_observations
count          5.500000e+02            550.000000
mean           1.678112e+07             44.809091
std            3.695175e+06            102.224929
min            8.035804e+06              1.000000
25%            1.358551e+07              5.000000
50%            1.741242e+07              8.000000
75%            1.978977e+07             30.000000
max            2.813860e+07           1344.000000

evidence

In [ ]:
import pandas as pd
import numpy as np

file = "/content/drive/MyDrive/DataSetForpython/weather.csv"

df = pd.read_csv(file)

print("Shape:", df.shape)
print(df.columns.tolist())

Shape: (552, 38)
['HOTSPOT_ID', 'total_detections', 'unique_days', 'unique_months', 'first_detection', 'last_detection', 'mean_FRP', 'max_FRP', 'active_duration_days', 'hotspot_latitude', 'hotspot_longitude', 'distance_to_industrial_km', 'distance_to_power_km', 'distance_to_mining_km', 'distance_to_fuel_storage_km', 'distance_to_agriculture_km', 'distance_to_transport_km', 'dominant_land_cover', 'land_cover_observations', 'lc_water_ratio', 'lc_trees_ratio', 'lc_grass_ratio', 'lc_flooded_vegetation_ratio', 'lc_crops_ratio', 'lc_shrub_and_scrub_ratio', 'lc_built_ratio', 'lc_bare_ratio', 'lc_snow_and_ice_ratio', 'mean_temperature', 'max_temperature', 'min_temperature', 'mean_wind_speed', 'max_wind_speed', 'mean_dewpoint', 'mean_precipitation', 'total_precipitation', 'mean_solar_radiation', 'weather_observations']

In [ ]:
evidence_columns = [
    "HOTSPOT_ID",
    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",
    "distance_to_transport_km",
    "dominant_land_cover",
    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_bare_ratio",
    "lc_trees_ratio",
    "lc_grass_ratio",
    "total_detections",
    "unique_days",
    "unique_months",
    "mean_FRP",
    "max_FRP"
]

display(df[evidence_columns].head(20))

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,distance_to_transport_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
0,26,15.578091,373.490365,19.217704,34.041174,39.575294,15.746427,bare,0.000000,0.418919,0.581081,0.000000,0.0,74,70,21,0.902973,4.03
1,27,12.644410,410.451406,0.829036,4.538796,30.823322,33.024747,bare,0.000000,0.287846,0.712154,0.000000,0.0,514,269,21,1.131848,4.24
2,28,0.501288,583.763570,1.702899,6.729748,3.341023,0.467309,built,0.000000,0.733129,0.266871,0.000000,0.0,326,282,24,1.388344,5.13
3,29,0.095234,600.653677,1.585191,12.064471,8.499625,1.650086,bare,0.000000,0.451923,0.524038,0.000000,0.0,208,183,21,1.407692,4.90
4,30,0.570174,12.259274,59.520224,116.206757,106.463072,100.749367,crops,0.789062,0.203125,0.000000,0.007812,0.0,129,106,20,0.833721,2.93
5,31,0.169107,5.543293,20.084768,211.404492,193.959031,221.139018,bare,0.052632,0.060729,0.862348,0.000000,0.0,247,228,23,1.134939,4.82
6,32,0.206351,4.351976,20.651400,212.969854,195.521549,222.697658,bare,0.000000,0.156250,0.843750,0.000000,0.0,33,33,13,0.876061,1.55
7,33,4.431123,12.574271,1.253243,231.260516,213.402150,243.729536,bare,0.036145,0.156627,0.759036,0.000000,0.0,83,81,15,0.668434,1.32
8,34,0.433238,12.506674,3.571421,231.314071,213.436947,242.605640,built,0.031088,0.792746,0.020725,0.000000,0.0,350,221,23,1.126057,18.31
9,35,0.647935,1.751156,6.826338,255.188344,237.282468,266.522546,built,0.000000,0.859504,0.132231,0.008264,0.0,200,135,22,2.180950,17.93
10,71,0.107511,65.245378,3.738666,20.742069,15.030742,17.204222,built,0.000000,0.797753,0.022472,0.168539,0.0,232,189,24,0.725431,5.80
11,75,0.314030,145.832221,1.508706,17.881779,19.714139,29.940179,built,0.000000,0.610224,0.389776,0.000000,0.0,319,230,23,1.405423,4.88
12,76,8.960064,412.027324,1.472609,10.776332,36.542704,39.240013,built,0.000000,0.531915,0.468085,0.000000,0.0,98,89,20,0.815408,1.69
13,77,0.150550,411.130378,5.812474,29.324903,15.013996,0.231602,built,0.000000,1.000000,0.000000,0.000000,0.0,142,139,22,0.935986,3.71
14,78,0.510952,503.576095,2.146364,16.693276,5.710664,0.505381,bare,0.000000,0.421442,0.578558,0.000000,0.0,543,360,23,1.762431,6.31
15,79,4.038723,9.029609,65.065715,117.172285,111.033581,106.660306,crops,0.565657,0.434343,0.000000,0.000000,0.0,103,87,15,0.775146,3.33
16,80,0.131049,3.087866,11.095306,241.657773,223.888965,252.392874,bare,0.000000,0.300000,0.600000,0.000000,0.0,20,20,8,0.676500,1.02
17,81,0.194546,7.352366,15.180115,249.091727,231.390368,259.483931,bare,0.000000,0.330000,0.660000,0.000000,0.0,100,98,19,0.908200,5.67
18,132,6.177422,27.890424,48.503921,6.646655,1.559411,8.245157,crops,0.613636,0.000000,0.227273,0.000000,0.0,50,45,18,0.731600,3.62
19,133,6.230366,33.781286,39.692573,5.838137,4.967165,7.155072,crops,0.833333,0.000000,0.166667,0.000000,0.0,12,10,6,0.896667,1.97

In [ ]:
def assign_label(row):

    industrial_score = 0
    agriculture_score = 0
    mining_score = 0

    # -----------------------------
    # INDUSTRIAL EVIDENCE
    # -----------------------------

    if pd.notna(row["distance_to_industrial_km"]):
        if row["distance_to_industrial_km"] <= 0.5:
            industrial_score += 3
        elif row["distance_to_industrial_km"] <= 2:
            industrial_score += 1

    if pd.notna(row["distance_to_power_km"]):
        if row["distance_to_power_km"] <= 1:
            industrial_score += 1

    if pd.notna(row["distance_to_fuel_storage_km"]):
        if row["distance_to_fuel_storage_km"] <= 2:
            industrial_score += 2

    if row["lc_built_ratio"] >= 0.5:
        industrial_score += 2


    # -----------------------------
    # AGRICULTURAL / VEGETATION
    # -----------------------------

    if row["lc_crops_ratio"] >= 0.5:
        agriculture_score += 3

    elif row["lc_crops_ratio"] >= 0.3:
        agriculture_score += 2

    if row["lc_grass_ratio"] >= 0.4:
        agriculture_score += 1

    if row["lc_trees_ratio"] >= 0.5:
        agriculture_score += 1

    if pd.notna(row["distance_to_agriculture_km"]):
        if row["distance_to_agriculture_km"] <= 1:
            agriculture_score += 2


    # -----------------------------
    # MINING
    # -----------------------------

    if pd.notna(row["distance_to_mining_km"]):

        if row["distance_to_mining_km"] <= 2:
            mining_score += 3

        elif row["distance_to_mining_km"] <= 5:
            mining_score += 2

    if row["lc_bare_ratio"] >= 0.5:
        mining_score += 1


    # -----------------------------
    # SELECT CLASS
    # -----------------------------

    scores = {
        "Agricultural_Vegetation": agriculture_score,
        "Industrial": industrial_score,
        "Mining_Extraction": mining_score
    }

    best_class = max(scores, key=scores.get)
    best_score = scores[best_class]

    # Require reasonable evidence
    if best_score < 3:
        return "Other_Persistent_Thermal_Source"

    # If two classes are too close, don't force a label
    sorted_scores = sorted(
        scores.values(),
        reverse=True
    )

    if len(sorted_scores) >= 2:
        if sorted_scores[0] - sorted_scores[1] < 2:
            return "Needs_Review"

    return best_class

In [ ]:
df["provisional_label"] = df.apply(
    assign_label,
    axis=1
)

In [ ]:
print(
    df["provisional_label"].value_counts()
)

provisional_label
Agricultural_Vegetation            250
Other_Persistent_Thermal_Source    178
Industrial                          78
Needs_Review                        28
Mining_Extraction                   18
Name: count, dtype: int64

In [ ]:
# Show representative examples from each class

for label in [
    "Agricultural_Vegetation",
    "Industrial",
    "Mining_Extraction",
    "Other_Persistent_Thermal_Source",
    "Needs_Review"
]:

    print("\n" + "="*70)
    print(label)
    print("="*70)

    display(
        df[df["provisional_label"] == label][[
            "HOTSPOT_ID",
            "distance_to_industrial_km",
            "distance_to_power_km",
            "distance_to_mining_km",
            "distance_to_fuel_storage_km",
            "distance_to_agriculture_km",
            "dominant_land_cover",
            "lc_crops_ratio",
            "lc_built_ratio",
            "lc_bare_ratio",
            "lc_trees_ratio",
            "lc_grass_ratio",
            "total_detections",
            "unique_days",
            "unique_months",
            "mean_FRP",
            "max_FRP"
        ]].sample(
            min(10, len(df[df["provisional_label"] == label])),
            random_state=42
        )
    )

======================================================================
Agricultural_Vegetation
======================================================================

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
306,39118,159.244890,154.015469,200.762918,NaN,NaN,crops,1.000000,0.000000,0.0,0.0,0.0,19,17,7,4.655789,11.39
44,706,3.597548,19.192567,56.141474,101.903336,98.688137,crops,0.666667,0.333333,0.0,0.0,0.0,12,11,9,0.810000,2.37
180,12567,3.132871,39.490725,24.902207,11.639473,0.136556,crops,1.000000,0.000000,0.0,0.0,0.0,22,13,6,4.072273,8.72
140,7939,152.015861,356.851394,155.563818,150.223209,153.978873,crops,1.000000,0.000000,0.0,0.0,0.0,23,12,6,6.343478,19.34
196,15399,5.806889,40.009167,22.230644,13.335176,2.630084,crops,0.777778,0.222222,0.0,0.0,0.0,24,13,6,9.611250,18.29
459,50740,152.290271,123.560301,141.758104,NaN,NaN,crops,1.000000,0.000000,0.0,0.0,0.0,61,15,6,3.088197,12.99
478,54458,3.395586,3.786688,17.621399,NaN,NaN,crops,1.000000,0.000000,0.0,0.0,0.0,57,23,6,8.710175,26.75
462,51131,135.946146,108.495267,126.428245,NaN,NaN,crops,1.000000,0.000000,0.0,0.0,0.0,233,30,6,3.163820,15.51
69,1396,5.694870,28.290791,22.083884,20.599760,5.686607,crops,1.000000,0.000000,0.0,0.0,0.0,25,14,8,4.892400,13.08
188,13778,36.915960,346.178192,37.735398,56.170713,19.321796,crops,1.000000,0.000000,0.0,0.0,0.0,18,12,6,5.605556,11.86

======================================================================
Industrial
======================================================================

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
118,6067,1.370723,22.504046,5.165401,4.232781,3.814104,built,0.000000,0.962963,0.037037,0.000000,0.0,28,26,8,0.620357,1.18
5,31,0.169107,5.543293,20.084768,211.404492,193.959031,bare,0.052632,0.060729,0.862348,0.000000,0.0,247,228,23,1.134939,4.82
148,8304,0.242389,71.941227,2.108914,4.041219,11.128797,built,0.000000,0.625000,0.375000,0.000000,0.0,24,23,10,0.718333,1.04
27,182,0.159850,14.242948,5.699753,229.437525,211.604493,built,0.137931,0.689655,0.068966,0.000000,0.0,29,26,13,0.641724,1.55
21,135,0.266814,393.043793,1.574318,20.644570,32.251935,built,0.000000,0.555556,0.444444,0.000000,0.0,270,178,22,1.373037,3.17
472,53393,0.194689,1.295222,7.475163,NaN,NaN,built,0.000000,1.000000,0.000000,0.000000,0.0,57,54,12,0.723333,1.37
86,2220,0.690422,391.518186,48.116661,29.737889,26.811968,built,0.000000,0.800000,0.000000,0.200000,0.0,15,11,6,1.790667,4.23
10,71,0.107511,65.245378,3.738666,20.742069,15.030742,built,0.000000,0.797753,0.022472,0.168539,0.0,232,189,24,0.725431,5.80
246,38634,0.208049,1.424411,3.794394,NaN,NaN,built,0.000000,0.911063,0.073753,0.000000,0.0,461,372,22,1.420672,4.52
349,39794,0.396508,1.046548,7.919649,NaN,NaN,built,0.045455,0.727273,0.045455,0.136364,0.0,30,20,16,3.957667,12.84

======================================================================
Mining_Extraction
======================================================================

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
1,27,12.644410,410.451406,0.829036,4.538796,30.823322,bare,0.000000,0.287846,0.712154,0.000000,0.0,514,269,21,1.131848,4.24
7,33,4.431123,12.574271,1.253243,231.260516,213.402150,bare,0.036145,0.156627,0.759036,0.000000,0.0,83,81,15,0.668434,1.32
270,38792,0.811132,7.102050,0.590721,NaN,NaN,shrub_and_scrub,0.000000,0.000000,0.000000,0.235294,0.0,17,16,8,0.757647,1.34
231,38617,2.267870,10.603573,0.574246,NaN,NaN,bare,0.008403,0.338936,0.647059,0.000000,0.0,531,307,23,1.582335,8.74
51,917,0.564954,498.307323,1.286411,11.897199,0.710378,bare,0.000000,0.162162,0.770270,0.000000,0.0,76,72,17,1.224737,7.71
354,39919,1.286247,16.405600,0.365022,NaN,NaN,bare,0.000000,0.000000,1.000000,0.000000,0.0,19,16,7,1.148947,2.40
547,64531,5.753075,6.832885,0.506906,NaN,NaN,bare,0.000000,0.000000,0.791667,0.000000,0.0,92,66,10,1.391739,7.40
457,50700,2.218329,2.245958,0.116467,NaN,NaN,bare,0.017182,0.065292,0.903780,0.000000,0.0,382,147,13,3.638534,18.44
330,39354,0.702337,6.135123,1.175946,NaN,NaN,trees,0.000000,0.250000,0.000000,0.625000,0.0,16,16,8,1.441250,8.27
14,78,0.510952,503.576095,2.146364,16.693276,5.710664,bare,0.000000,0.421442,0.578558,0.000000,0.0,543,360,23,1.762431,6.31

======================================================================
Other_Persistent_Thermal_Source
======================================================================

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
67,1340,2.466619,37.141714,47.594138,2.761842,2.544152,built,0.263158,0.631579,0.000000,0.052632,0.000000,20,16,8,0.798000,1.45
237,38625,86.422914,87.137845,99.767439,NaN,NaN,built,0.022422,0.630045,0.336323,0.000000,0.000000,447,323,22,1.477405,10.67
419,42697,62.178177,77.067025,57.097843,NaN,NaN,shrub_and_scrub,0.153846,0.000000,0.000000,0.307692,0.153846,21,15,8,7.298095,15.40
105,5182,54.530973,64.750170,61.191709,64.214895,48.821409,trees,0.000000,0.000000,0.000000,1.000000,0.000000,22,10,6,4.012727,10.25
297,39089,1.828686,0.048935,10.899928,NaN,NaN,bare,0.000000,0.039216,0.921569,0.039216,0.000000,56,46,10,0.682143,1.17
62,1280,24.481956,109.342170,26.771574,23.963641,29.522508,water,0.000000,0.000000,0.000000,0.000000,0.000000,29,17,7,9.742069,29.90
382,40541,100.523064,98.336965,106.823724,NaN,NaN,built,0.000000,0.687500,0.187500,0.062500,0.000000,17,16,8,1.605294,8.94
545,64479,37.138689,42.317179,38.737649,NaN,NaN,trees,0.074074,0.287037,0.138889,0.398148,0.000000,108,90,15,0.915185,2.85
366,40140,89.421769,115.508780,100.592331,NaN,NaN,bare,0.000000,0.000000,1.000000,0.000000,0.000000,35,29,13,2.090857,6.89
421,42827,91.614317,116.538335,101.536212,NaN,NaN,water,0.000000,0.263158,0.315789,0.105263,0.000000,22,19,6,0.819545,4.06

======================================================================
Needs_Review
======================================================================

,HOTSPOT_ID,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,dominant_land_cover,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,total_detections,unique_days,unique_months,mean_FRP,max_FRP
93,2714,0.117998,30.711146,10.941017,4.516504,4.472516,crops,0.573770,0.409836,0.016393,0.000000,0.0,65,61,16,0.698923,3.02
468,52070,0.294906,2.984804,52.081985,NaN,NaN,crops,0.555556,0.222222,0.000000,0.000000,0.0,15,13,8,3.998667,14.33
87,2233,4.010522,23.325468,4.903927,4.986768,4.125356,crops,0.971429,0.000000,0.000000,0.028571,0.0,71,57,13,0.795352,2.04
337,39494,0.045555,5.714988,0.234171,NaN,NaN,bare,0.000000,0.142857,0.857143,0.000000,0.0,14,14,6,0.879286,3.21
2,28,0.501288,583.763570,1.702899,6.729748,3.341023,built,0.000000,0.733129,0.266871,0.000000,0.0,326,282,24,1.388344,5.13
252,38646,0.078169,12.829935,0.990898,NaN,NaN,trees,0.000000,0.395225,0.000000,0.541114,0.0,377,285,22,1.302971,9.56
292,38958,0.025375,5.719276,1.675976,NaN,NaN,bare,0.000000,0.210884,0.482993,0.074830,0.0,169,136,21,1.576391,9.46
399,41288,3.111349,10.651168,2.529132,NaN,NaN,crops,0.621622,0.378378,0.000000,0.000000,0.0,37,30,16,1.081081,2.61
198,16134,3.672899,69.825790,3.628412,10.972763,3.778920,crops,1.000000,0.000000,0.000000,0.000000,0.0,27,11,6,6.453333,13.09
284,38858,0.099882,0.155377,2.112822,NaN,NaN,bare,0.000000,0.000000,1.000000,0.000000,0.0,24,23,6,0.999167,1.43

In [ ]:
import pandas as pd
import numpy as np

# ============================================================
# 1. LOAD DATASET
# ============================================================

df = pd.read_csv("/content/drive/MyDrive/DataSetForpython/weather.csv")

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (552, 38)

Columns:
['HOTSPOT_ID', 'total_detections', 'unique_days', 'unique_months', 'first_detection', 'last_detection', 'mean_FRP', 'max_FRP', 'active_duration_days', 'hotspot_latitude', 'hotspot_longitude', 'distance_to_industrial_km', 'distance_to_power_km', 'distance_to_mining_km', 'distance_to_fuel_storage_km', 'distance_to_agriculture_km', 'distance_to_transport_km', 'dominant_land_cover', 'land_cover_observations', 'lc_water_ratio', 'lc_trees_ratio', 'lc_grass_ratio', 'lc_flooded_vegetation_ratio', 'lc_crops_ratio', 'lc_shrub_and_scrub_ratio', 'lc_built_ratio', 'lc_bare_ratio', 'lc_snow_and_ice_ratio', 'mean_temperature', 'max_temperature', 'min_temperature', 'mean_wind_speed', 'max_wind_speed', 'mean_dewpoint', 'mean_precipitation', 'total_precipitation', 'mean_solar_radiation', 'weather_observations']

In [ ]:
# Columns we expect to use for labeling
label_columns = [
    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",
    "dominant_land_cover",
    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_trees_ratio",
    "lc_grass_ratio",
    "lc_shrub_and_scrub_ratio",
    "lc_bare_ratio",
    "unique_days",
    "unique_months",
    "mean_frp",
    "max_frp"
]

for col in label_columns:
    if col in df.columns:
        print(f"✓ {col}")
    else:
        print(f"✗ MISSING: {col}")

✓ distance_to_industrial_km
✓ distance_to_power_km
✓ distance_to_mining_km
✓ distance_to_fuel_storage_km
✓ distance_to_agriculture_km
✓ dominant_land_cover
✓ lc_crops_ratio
✓ lc_built_ratio
✓ lc_trees_ratio
✓ lc_grass_ratio
✓ lc_shrub_and_scrub_ratio
✓ lc_bare_ratio
✓ unique_days
✓ unique_months
✗ MISSING: mean_frp
✗ MISSING: max_frp

In [ ]:
# ============================================================
# INDUSTRIAL SCORE
# ============================================================

df["industrial_score"] = 0.0

# Industrial proximity
df.loc[
    df["distance_to_industrial_km"] <= 0.5,
    "industrial_score"
] += 0.45

df.loc[
    (df["distance_to_industrial_km"] > 0.5) &
    (df["distance_to_industrial_km"] <= 2),
    "industrial_score"
] += 0.25


# Power infrastructure
df.loc[
    df["distance_to_power_km"] <= 1,
    "industrial_score"
] += 0.20


# Fuel/storage infrastructure
df.loc[
    df["distance_to_fuel_storage_km"] <= 2,
    "industrial_score"
] += 0.20


# Built-up land cover
df.loc[
    df["dominant_land_cover"] == "built",
    "industrial_score"
] += 0.15


# Cap score
df["industrial_score"] = df["industrial_score"].clip(upper=1.0)

In [ ]:
# ============================================================
# AGRICULTURE / VEGETATION SCORE
# ============================================================

df["agriculture_score"] = 0.0


# Crops dominant
df.loc[
    df["dominant_land_cover"] == "crops",
    "agriculture_score"
] += 0.45


# Crops ratio
df.loc[
    df["lc_crops_ratio"] >= 0.70,
    "agriculture_score"
] += 0.30

df.loc[
    (df["lc_crops_ratio"] >= 0.40) &
    (df["lc_crops_ratio"] < 0.70),
    "agriculture_score"
] += 0.20


# Agriculture OSM proximity
df.loc[
    df["distance_to_agriculture_km"] <= 1,
    "agriculture_score"
] += 0.25


# Vegetation context
df.loc[
    df["dominant_land_cover"].isin([
        "grass",
        "trees",
        "shrub_and_scrub"
    ]),
    "agriculture_score"
] += 0.15


# Cap
df["agriculture_score"] = df["agriculture_score"].clip(upper=1.0)

In [ ]:
# ============================================================
# MINING / EXTRACTION SCORE
# ============================================================

df["mining_score"] = 0.0


# Very close mining/quarry feature
df.loc[
    df["distance_to_mining_km"] <= 1,
    "mining_score"
] += 0.55


# Somewhat close
df.loc[
    (df["distance_to_mining_km"] > 1) &
    (df["distance_to_mining_km"] <= 5),
    "mining_score"
] += 0.30


# Bare land
df.loc[
    df["dominant_land_cover"] == "bare",
    "mining_score"
] += 0.30


# Shrubland can support extraction context
df.loc[
    df["dominant_land_cover"] == "shrub_and_scrub",
    "mining_score"
] += 0.10


# Cap
df["mining_score"] = df["mining_score"].clip(upper=1.0)

In [ ]:
# ============================================================
# DETERMINE STRONGEST EVIDENCE
# ============================================================

score_cols = [
    "industrial_score",
    "agriculture_score",
    "mining_score"
]

df["best_score"] = df[score_cols].max(axis=1)

df["second_best_score"] = (
    df[score_cols]
    .apply(lambda row: sorted(row, reverse=True)[1], axis=1)
)

df["score_margin"] = (
    df["best_score"] - df["second_best_score"]
)


def get_best_class(row):

    scores = {
        "Industrial": row["industrial_score"],
        "Agricultural_Vegetation": row["agriculture_score"],
        "Mining_Extraction": row["mining_score"]
    }

    return max(scores, key=scores.get)


df["evidence_class"] = df.apply(get_best_class, axis=1)

In [ ]:
# ============================================================
# CONFIDENCE
# ============================================================

def confidence(row):

    score = row["best_score"]
    margin = row["score_margin"]

    if score >= 0.70 and margin >= 0.25:
        return "High"

    elif score >= 0.50 and margin >= 0.15:
        return "Medium"

    else:
        return "Low"


df["label_confidence"] = df.apply(confidence, axis=1)

In [ ]:
# ============================================================
# PROVISIONAL LABEL
# ============================================================

def assign_label(row):

    if row["label_confidence"] == "Low":
        return "Needs_Review"

    return row["evidence_class"]


df["provisional_label"] = df.apply(assign_label, axis=1)

In [ ]:
print("\n========== LABEL DISTRIBUTION ==========\n")

print(
    df["provisional_label"]
    .value_counts()
)

print("\n========== CONFIDENCE ==========\n")

print(
    pd.crosstab(
        df["provisional_label"],
        df["label_confidence"]
    )
)

========== LABEL DISTRIBUTION ==========

provisional_label
Agricultural_Vegetation    264
Needs_Review               213
Industrial                  56
Mining_Extraction           19
Name: count, dtype: int64

========== CONFIDENCE ==========

label_confidence         High  Low  Medium
provisional_label
Agricultural_Vegetation   239    0      25
Industrial                 10    0      46
Mining_Extraction          10    0       9
Needs_Review                0  213       0

In [ ]:
# ============================================================
# ADD OTHER PERSISTENT THERMAL SOURCE
# ============================================================

def final_provisional_label(row):

    # Strong enough evidence
    if row["best_score"] >= 0.50:

        # But if competition between classes is too close,
        # send it for review
        if row["score_margin"] < 0.15:
            return "Needs_Review"

        return row["evidence_class"]

    # No strong contextual evidence
    return "Other_Persistent_Thermal_Source"


df["provisional_label"] = df.apply(
    final_provisional_label,
    axis=1
)

In [ ]:
print(
    df["provisional_label"]
    .value_counts()
)

provisional_label
Agricultural_Vegetation            264
Other_Persistent_Thermal_Source    206
Industrial                          56
Mining_Extraction                   19
Needs_Review                         7
Name: count, dtype: int64

In [ ]:
# ============================================================
# EVIDENCE TABLE
# ============================================================

evidence_columns = [
    "HOTSPOT_ID",
    "hotspot_latitude",
    "hotspot_longitude",

    "provisional_label",
    "label_confidence",

    "industrial_score",
    "agriculture_score",
    "mining_score",

    "best_score",
    "second_best_score",
    "score_margin",

    "dominant_land_cover",
    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_bare_ratio",

    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",

    "unique_days",
    "unique_months",
    "mean_frp",
    "max_frp"
]

# Keep only columns that actually exist
evidence_columns = [
    c for c in evidence_columns
    if c in df.columns
]

evidence_df = df[evidence_columns].copy()

print(evidence_df.shape)
display(evidence_df.head(10))

(552, 22)

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
0,26,27.080394,73.817179,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.30,0.30,0.00,...,0.000000,0.418919,0.581081,15.578091,373.490365,19.217704,34.041174,39.575294,70,21
1,27,26.876586,73.515424,Mining_Extraction,High,0.00,0.00,0.85,0.85,0.00,...,0.000000,0.287846,0.712154,12.644410,410.451406,0.829036,4.538796,30.823322,269,21
2,28,24.821264,73.093785,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.30,0.40,0.30,...,0.000000,0.733129,0.266871,0.501288,583.763570,1.702899,6.729748,3.341023,282,24
3,29,24.690245,73.002674,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.451923,0.524038,0.095234,600.653677,1.585191,12.064471,8.499625,183,21
4,30,23.408204,72.416596,Agricultural_Vegetation,High,0.25,0.75,0.00,0.75,0.25,...,0.789062,0.203125,0.000000,0.570174,12.259274,59.520224,116.206757,106.463072,106,20
5,31,23.315243,70.487057,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.052632,0.060729,0.862348,0.169107,5.543293,20.084768,211.404492,193.959031,228,23
6,32,23.304789,70.476777,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.156250,0.843750,0.206351,4.351976,20.651400,212.969854,195.521549,33,13
7,33,23.313702,70.199973,Mining_Extraction,Medium,0.00,0.00,0.60,0.60,0.00,...,0.036145,0.156627,0.759036,4.431123,12.574271,1.253243,231.260516,213.402150,81,15
8,34,23.263791,70.257548,Industrial,Medium,0.60,0.00,0.30,0.60,0.30,...,0.031088,0.792746,0.020725,0.433238,12.506674,3.571421,231.314071,213.436947,221,23
9,35,23.118267,70.084872,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.859504,0.132231,0.647935,1.751156,6.826338,255.188344,237.282468,135,22

In [ ]:
review_df = evidence_df[
    evidence_df["provisional_label"] == "Needs_Review"
].copy()

review_df = review_df.sort_values(
    "best_score"
)

display(review_df)

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
252,38646,15.658527,73.988879,Needs_Review,Low,0.45,0.15,0.55,0.55,0.45,...,0.000000,0.395225,0.000000,0.078169,12.829935,0.990898,NaN,NaN,285,22
3,29,24.690245,73.002674,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.451923,0.524038,0.095234,600.653677,1.585191,12.064471,8.499625,183,21
285,38859,19.787393,79.063342,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.190476,0.809524,0.145882,13.864859,1.038567,NaN,NaN,20,10
292,38958,15.525906,73.994028,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.210884,0.482993,0.025375,5.719276,1.675976,NaN,NaN,136,21
391,40868,19.936474,73.711858,Needs_Review,Low,0.60,0.00,0.55,0.60,0.55,...,0.053097,0.707965,0.008850,0.188841,3.597486,0.144736,NaN,NaN,93,20
284,38858,19.930050,79.120400,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.000000,1.000000,0.099882,0.155377,2.112822,NaN,NaN,23,6
317,39182,23.497204,68.578189,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.294521,0.705479,0.139267,0.245869,1.073055,NaN,NaN,119,20

In [ ]:
other_df = evidence_df[
    evidence_df["provisional_label"] ==
    "Other_Persistent_Thermal_Source"
].copy()

other_df = other_df.sort_values(
    "best_score",
    ascending=False
)

display(other_df.head(50))

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
6,32,23.304789,70.476777,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.156250,0.843750,0.206351,4.351976,20.651400,212.969854,195.521549,33,13
5,31,23.315243,70.487057,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.052632,0.060729,0.862348,0.169107,5.543293,20.084768,211.404492,193.959031,228,23
17,81,23.105164,70.188032,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.330000,0.660000,0.194546,7.352366,15.180115,249.091727,231.390368,98,19
16,80,23.170343,70.218120,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.300000,0.600000,0.131049,3.087866,11.095306,241.657773,223.888965,20,8
53,969,27.467406,71.981374,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.000000,1.000000,0.347843,529.352336,94.042167,47.989042,29.863074,11,9
40,523,23.013945,70.102891,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.019048,0.176190,0.771429,0.102608,10.027297,8.534281,NaN,NaN,177,19
230,38611,21.105104,72.640954,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.328869,0.671131,0.276135,1.613707,52.566936,NaN,NaN,578,24
60,1265,28.251841,73.249360,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.000000,1.000000,0.467078,390.509353,31.386554,22.298924,22.597211,16,8
268,38786,21.233418,79.629771,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.367347,0.629252,0.249435,16.733453,32.503944,NaN,NaN,228,21
256,38706,21.683964,72.536954,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.000000,0.058824,0.352941,0.158078,4.864759,33.627793,NaN,NaN,20,6
499,59472,20.129992,79.112149,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.3,0.45,0.30,...,0.388889,0.000000,0.314815,7.899936,15.698638,1.756776,NaN,NaN,49,11
365,40112,21.342496,72.998922,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.238095,0.000000,0.285714,0.889591,0.165534,7.603277,NaN,NaN,10,8
297,39089,20.006386,79.183813,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.039216,0.921569,1.828686,0.048935,10.899928,NaN,NaN,46,10
282,38855,22.907231,69.873321,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.062500,0.083333,0.812500,0.169974,2.605528,14.885130,NaN,NaN,46,14
447,48131,18.717034,73.858276,Other_Persistent_Thermal_Source,Low,0.45,0.45,0.3,0.45,0.45,...,0.357143,0.214286,0.000000,0.481220,13.234756,3.185714,NaN,NaN,11,6
540,63191,21.066649,72.886287,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.0,0.45,0.00,...,0.384615,0.230769,0.000000,2.328493,9.003823,37.418597,NaN,NaN,10,7
439,45180,21.693999,72.604870,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.333333,0.190476,0.000000,0.050578,1.206592,40.568015,NaN,NaN,10,8
257,38707,21.099409,72.844642,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.937500,0.000000,1.419093,10.295067,36.918232,NaN,NaN,20,8
73,1611,28.828508,77.155422,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.133333,0.866667,0.000000,1.924938,16.705143,47.567620,4.763114,3.001412,22,11
80,1918,29.475278,76.858158,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.193548,0.483871,0.064516,0.981479,94.192663,92.192991,2.912699,7.022535,22,8
98,2974,28.819840,77.164795,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.227273,0.772727,0.000000,1.676527,15.496888,46.528372,5.052450,3.730764,21,9
357,39952,18.820330,73.288877,Other_Persistent_Thermal_Source,Low,0.25,0.15,0.4,0.40,0.25,...,0.000000,0.285714,0.000000,0.957335,6.276317,3.832147,NaN,NaN,10,6
299,39096,18.369104,73.291764,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,5.456982,8.558911,3.317185,NaN,NaN,13,8
86,2220,25.155066,76.179023,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.800000,0.000000,0.690422,391.518186,48.116661,29.737889,26.811968,11,6
264,38765,18.323032,73.324170,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,7.093965,10.330999,1.243336,NaN,NaN,19,9
245,38633,21.759914,71.950280,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.173913,0.826087,0.000000,0.502732,13.258698,28.141034,NaN,NaN,25,12
24,150,29.909731,74.949037,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.330508,0.411017,0.182203,1.093745,156.625245,63.165110,33.891244,8.290464,146,23
118,6067,28.346604,77.257296,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.962963,0.037037,1.370723,22.504046,5.165401,4.232781,3.814104,26,8
9,35,23.118267,70.084872,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.859504,0.132231,0.647935,1.751156,6.826338,255.188344,237.282468,135,22
2,28,24.821264,73.093785,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,0.733129,0.266871,0.501288,583.763570,1.702899,6.729748,3.341023,282,24
422,42832,19.503330,73.590765,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,2.277942,6.981300,4.487946,NaN,NaN,10,6
331,39355,19.082186,73.035597,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,0.708333,0.041667,0.954160,8.603407,1.093482,NaN,NaN,23,12
288,38900,22.787922,70.917860,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.081081,0.567568,0.324324,0.726165,6.953870,1.834947,NaN,NaN,34,11
324,39256,20.355694,72.949392,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.018519,0.703704,0.000000,1.051274,10.264520,12.048941,NaN,NaN,46,15
307,39123,22.365439,73.116067,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.936170,0.000000,0.616093,1.447780,34.138781,NaN,NaN,158,21
487,57692,18.456401,73.944091,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,1.000000,0.000000,0.981622,9.002225,4.420931,NaN,NaN,21,12
240,38628,22.937750,69.697498,Other_Persistent_Thermal_Source,Low,0.35,0.00,0.0,0.35,0.00,...,0.133929,0.446429,0.160714,4.575310,0.840901,15.104222,NaN,NaN,87,7
39,470,26.258041,74.095892,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.046358,0.549669,0.390728,5.548145,400.941857,4.296211,24.153096,27.246037,142,19
224,23801,27.502409,72.412583,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.000000,1.000000,6.263001,487.212593,60.124176,36.466624,6.896706,12,9
272,38794,17.584512,80.318238,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.180723,0.710843,206.189454,266.094600,227.523645,NaN,NaN,85,19
267,38783,21.085780,74.355044,Other_Persistent_Thermal_Source,Low,0.20,0.00,0.3,0.30,0.20,...,0.033333,0.100000,0.366667,16.148598,0.326264,48.789021,NaN,NaN,11,7
32,323,23.055313,69.994720,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.047619,0.571429,0.333333,2.906319,2.158064,1.293785,266.574628,248.681912,19,9
25,160,24.578942,74.803363,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.238532,0.761468,5.161430,503.167576,14.800834,10.990651,18.311066,103,21
12,76,26.926807,73.468469,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.000000,0.531915,0.468085,8.960064,412.027324,1.472609,10.776332,36.542704,89,20
0,26,27.080394,73.817179,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.418919,0.581081,15.578091,373.490365,19.217704,34.041174,39.575294,70,21
61,1266,28.328547,73.436504,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.000000,1.000000,2.812845,371.221334,50.714095,30.666718,28.437210,16,7
290,38913,15.314481,76.253935,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.095890,0.863014,208.748297,196.437216,206.921046,NaN,NaN,78,20
289,38905,17.146115,78.223478,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.120219,0.087432,0.590164,179.075118,173.349563,176.026194,NaN,NaN,156,19
315,39180,15.175726,76.787122,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.040541,0.959459,249.705544,235.870906,264.273085,NaN,NaN,79,17
305,39114,14.992191,76.849581,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.038462,0.884615,271.029628,256.768104,272.555417,NaN,NaN,26,11

In [ ]:
evidence_df.to_csv(
    "/content/drive/MyDrive/DataSetForpython/hotspot_label_evidence.csv",
    index=False
)

print("Saved:")
print("hotspot_label_evidence.csv")

Saved:
hotspot_label_evidence.csv

In [ ]:
# ============================================================
# FINAL PROVISIONAL LABEL LOGIC - VERSION 2
# ============================================================

def assign_better_label(row):

    best = row["best_score"]
    margin = row["score_margin"]
    cls = row["evidence_class"]

    # --------------------------------------------------------
    # 1. HIGH-CONFIDENCE CASE
    # --------------------------------------------------------
    # Strong evidence AND clear winner
    if best >= 0.65 and margin >= 0.20:
        return cls

    # --------------------------------------------------------
    # 2. MEDIUM-CONFIDENCE CASE
    # --------------------------------------------------------
    # Reasonable evidence, but not strong enough to automatically
    # call it final
    if best >= 0.50 and margin >= 0.15:
        return cls

    # --------------------------------------------------------
    # 3. AMBIGUOUS CASE
    # --------------------------------------------------------
    # Two classes have relatively similar evidence
    if best >= 0.40 and margin < 0.15:
        return "Needs_Review"

    # --------------------------------------------------------
    # 4. LOW-EVIDENCE CASE
    # --------------------------------------------------------
    # None of the three categories has meaningful evidence
    if best < 0.40:
        return "Other_Persistent_Thermal_Source"

    # Anything sitting between the above conditions
    return "Needs_Review"


df["provisional_label"] = df.apply(
    assign_better_label,
    axis=1
)

In [ ]:
print("\n========== NEW LABEL DISTRIBUTION ==========\n")
print(df["provisional_label"].value_counts())

print("\n========== CONFIDENCE ==========\n")
print(
    pd.crosstab(
        df["provisional_label"],
        df["label_confidence"]
    )
)

========== NEW LABEL DISTRIBUTION ==========

provisional_label
Agricultural_Vegetation            264
Other_Persistent_Thermal_Source    170
Industrial                          56
Needs_Review                        43
Mining_Extraction                   19
Name: count, dtype: int64

========== CONFIDENCE ==========

label_confidence                 High  Low  Medium
provisional_label
Agricultural_Vegetation           239    0      25
Industrial                         10    0      46
Mining_Extraction                  10    0       9
Needs_Review                        0   43       0
Other_Persistent_Thermal_Source     0  170       0

In [ ]:
# ============================================================
# INSPECT OTHER HOTSPOTS
# ============================================================

other_df = evidence_df[
    evidence_df["provisional_label"] ==
    "Other_Persistent_Thermal_Source"
].copy()

print("Other hotspots:", len(other_df))

print("\nLand-cover distribution:")
print(other_df["dominant_land_cover"].value_counts(dropna=False))

print("\nScore statistics:")
print(
    other_df[
        ["industrial_score",
         "agriculture_score",
         "mining_score",
         "best_score"]
    ].describe()
)

Other hotspots: 206

Land-cover distribution:
dominant_land_cover
built              57
trees              53
bare               45
shrub_and_scrub    29
water              17
crops               3
NaN                 2
Name: count, dtype: int64

Score statistics:
       industrial_score  agriculture_score  mining_score  best_score
count        206.000000         206.000000    206.000000  206.000000
mean           0.110680           0.068204      0.110194    0.223301
std            0.153122           0.087631      0.139137    0.122637
min            0.000000           0.000000      0.000000    0.000000
25%            0.000000           0.000000      0.000000    0.150000
50%            0.000000           0.000000      0.000000    0.150000
75%            0.150000           0.150000      0.300000    0.300000
max            0.450000           0.450000      0.400000    0.450000

In [ ]:
# Show the 50 Other hotspots with strongest evidence
other_top = other_df.sort_values(
    "best_score",
    ascending=False
)

display(other_top.head(50))

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
6,32,23.304789,70.476777,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.156250,0.843750,0.206351,4.351976,20.651400,212.969854,195.521549,33,13
5,31,23.315243,70.487057,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.052632,0.060729,0.862348,0.169107,5.543293,20.084768,211.404492,193.959031,228,23
17,81,23.105164,70.188032,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.330000,0.660000,0.194546,7.352366,15.180115,249.091727,231.390368,98,19
16,80,23.170343,70.218120,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.300000,0.600000,0.131049,3.087866,11.095306,241.657773,223.888965,20,8
53,969,27.467406,71.981374,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.000000,1.000000,0.347843,529.352336,94.042167,47.989042,29.863074,11,9
40,523,23.013945,70.102891,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.019048,0.176190,0.771429,0.102608,10.027297,8.534281,NaN,NaN,177,19
230,38611,21.105104,72.640954,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.328869,0.671131,0.276135,1.613707,52.566936,NaN,NaN,578,24
60,1265,28.251841,73.249360,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.000000,1.000000,0.467078,390.509353,31.386554,22.298924,22.597211,16,8
268,38786,21.233418,79.629771,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.367347,0.629252,0.249435,16.733453,32.503944,NaN,NaN,228,21
256,38706,21.683964,72.536954,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.000000,0.058824,0.352941,0.158078,4.864759,33.627793,NaN,NaN,20,6
499,59472,20.129992,79.112149,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.3,0.45,0.30,...,0.388889,0.000000,0.314815,7.899936,15.698638,1.756776,NaN,NaN,49,11
365,40112,21.342496,72.998922,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.238095,0.000000,0.285714,0.889591,0.165534,7.603277,NaN,NaN,10,8
297,39089,20.006386,79.183813,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.000000,0.039216,0.921569,1.828686,0.048935,10.899928,NaN,NaN,46,10
282,38855,22.907231,69.873321,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.3,0.45,0.30,...,0.062500,0.083333,0.812500,0.169974,2.605528,14.885130,NaN,NaN,46,14
447,48131,18.717034,73.858276,Other_Persistent_Thermal_Source,Low,0.45,0.45,0.3,0.45,0.45,...,0.357143,0.214286,0.000000,0.481220,13.234756,3.185714,NaN,NaN,11,6
540,63191,21.066649,72.886287,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.0,0.45,0.00,...,0.384615,0.230769,0.000000,2.328493,9.003823,37.418597,NaN,NaN,10,7
439,45180,21.693999,72.604870,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.1,0.45,0.15,...,0.333333,0.190476,0.000000,0.050578,1.206592,40.568015,NaN,NaN,10,8
257,38707,21.099409,72.844642,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.937500,0.000000,1.419093,10.295067,36.918232,NaN,NaN,20,8
73,1611,28.828508,77.155422,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.133333,0.866667,0.000000,1.924938,16.705143,47.567620,4.763114,3.001412,22,11
80,1918,29.475278,76.858158,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.193548,0.483871,0.064516,0.981479,94.192663,92.192991,2.912699,7.022535,22,8
98,2974,28.819840,77.164795,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.227273,0.772727,0.000000,1.676527,15.496888,46.528372,5.052450,3.730764,21,9
357,39952,18.820330,73.288877,Other_Persistent_Thermal_Source,Low,0.25,0.15,0.4,0.40,0.25,...,0.000000,0.285714,0.000000,0.957335,6.276317,3.832147,NaN,NaN,10,6
299,39096,18.369104,73.291764,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,5.456982,8.558911,3.317185,NaN,NaN,13,8
86,2220,25.155066,76.179023,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.800000,0.000000,0.690422,391.518186,48.116661,29.737889,26.811968,11,6
264,38765,18.323032,73.324170,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,7.093965,10.330999,1.243336,NaN,NaN,19,9
245,38633,21.759914,71.950280,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.173913,0.826087,0.000000,0.502732,13.258698,28.141034,NaN,NaN,25,12
24,150,29.909731,74.949037,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.330508,0.411017,0.182203,1.093745,156.625245,63.165110,33.891244,8.290464,146,23
118,6067,28.346604,77.257296,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.962963,0.037037,1.370723,22.504046,5.165401,4.232781,3.814104,26,8
9,35,23.118267,70.084872,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.859504,0.132231,0.647935,1.751156,6.826338,255.188344,237.282468,135,22
2,28,24.821264,73.093785,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,0.733129,0.266871,0.501288,583.763570,1.702899,6.729748,3.341023,282,24
422,42832,19.503330,73.590765,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.4,0.40,0.15,...,0.000000,0.000000,0.000000,2.277942,6.981300,4.487946,NaN,NaN,10,6
331,39355,19.082186,73.035597,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,0.708333,0.041667,0.954160,8.603407,1.093482,NaN,NaN,23,12
288,38900,22.787922,70.917860,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.081081,0.567568,0.324324,0.726165,6.953870,1.834947,NaN,NaN,34,11
324,39256,20.355694,72.949392,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.018519,0.703704,0.000000,1.051274,10.264520,12.048941,NaN,NaN,46,15
307,39123,22.365439,73.116067,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.0,0.40,0.00,...,0.000000,0.936170,0.000000,0.616093,1.447780,34.138781,NaN,NaN,158,21
487,57692,18.456401,73.944091,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.3,0.40,0.30,...,0.000000,1.000000,0.000000,0.981622,9.002225,4.420931,NaN,NaN,21,12
240,38628,22.937750,69.697498,Other_Persistent_Thermal_Source,Low,0.35,0.00,0.0,0.35,0.00,...,0.133929,0.446429,0.160714,4.575310,0.840901,15.104222,NaN,NaN,87,7
39,470,26.258041,74.095892,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.046358,0.549669,0.390728,5.548145,400.941857,4.296211,24.153096,27.246037,142,19
224,23801,27.502409,72.412583,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.000000,1.000000,6.263001,487.212593,60.124176,36.466624,6.896706,12,9
272,38794,17.584512,80.318238,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.180723,0.710843,206.189454,266.094600,227.523645,NaN,NaN,85,19
267,38783,21.085780,74.355044,Other_Persistent_Thermal_Source,Low,0.20,0.00,0.3,0.30,0.20,...,0.033333,0.100000,0.366667,16.148598,0.326264,48.789021,NaN,NaN,11,7
32,323,23.055313,69.994720,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.047619,0.571429,0.333333,2.906319,2.158064,1.293785,266.574628,248.681912,19,9
25,160,24.578942,74.803363,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.238532,0.761468,5.161430,503.167576,14.800834,10.990651,18.311066,103,21
12,76,26.926807,73.468469,Other_Persistent_Thermal_Source,Low,0.15,0.00,0.3,0.30,0.15,...,0.000000,0.531915,0.468085,8.960064,412.027324,1.472609,10.776332,36.542704,89,20
0,26,27.080394,73.817179,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.418919,0.581081,15.578091,373.490365,19.217704,34.041174,39.575294,70,21
61,1266,28.328547,73.436504,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.000000,1.000000,2.812845,371.221334,50.714095,30.666718,28.437210,16,7
290,38913,15.314481,76.253935,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.095890,0.863014,208.748297,196.437216,206.921046,NaN,NaN,78,20
289,38905,17.146115,78.223478,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.120219,0.087432,0.590164,179.075118,173.349563,176.026194,NaN,NaN,156,19
315,39180,15.175726,76.787122,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.040541,0.959459,249.705544,235.870906,264.273085,NaN,NaN,79,17
305,39114,14.992191,76.849581,Other_Persistent_Thermal_Source,Low,0.00,0.00,0.3,0.30,0.00,...,0.000000,0.038462,0.884615,271.029628,256.768104,272.555417,NaN,NaN,26,11

In [ ]:
review_df = evidence_df[
    evidence_df["provisional_label"] ==
    "Needs_Review"
].copy()

print("Needs Review:", len(review_df))

display(
    review_df.sort_values(
        "best_score",
        ascending=False
    )
)

Needs Review: 7

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
284,38858,19.930050,79.120400,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.000000,1.000000,0.099882,0.155377,2.112822,NaN,NaN,23,6
317,39182,23.497204,68.578189,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.294521,0.705479,0.139267,0.245869,1.073055,NaN,NaN,119,20
3,29,24.690245,73.002674,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.451923,0.524038,0.095234,600.653677,1.585191,12.064471,8.499625,183,21
292,38958,15.525906,73.994028,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.210884,0.482993,0.025375,5.719276,1.675976,NaN,NaN,136,21
285,38859,19.787393,79.063342,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.190476,0.809524,0.145882,13.864859,1.038567,NaN,NaN,20,10
391,40868,19.936474,73.711858,Needs_Review,Low,0.60,0.00,0.55,0.60,0.55,...,0.053097,0.707965,0.008850,0.188841,3.597486,0.144736,NaN,NaN,93,20
252,38646,15.658527,73.988879,Needs_Review,Low,0.45,0.15,0.55,0.55,0.45,...,0.000000,0.395225,0.000000,0.078169,12.829935,0.990898,NaN,NaN,285,22

In [ ]:
print("========== BEST SCORE DISTRIBUTION ==========")

print(
    pd.cut(
        evidence_df["best_score"],
        bins=[0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0],
        include_lowest=True
    ).value_counts().sort_index()
)

========== BEST SCORE DISTRIBUTION ==========
best_score
(-0.001, 0.2]    119
(0.2, 0.3]        50
(0.3, 0.4]        20
(0.4, 0.5]        17
(0.5, 0.6]        56
(0.6, 0.7]        30
(0.7, 0.8]       246
(0.8, 1.0]        14
Name: count, dtype: int64

In [ ]:
# ============================================================
# BORDERLINE + REVIEW CASES
# ============================================================

borderline_df = evidence_df[
    (
        (evidence_df["best_score"] >= 0.40) &
        (evidence_df["best_score"] < 0.50)
    )
    |
    (evidence_df["provisional_label"] == "Needs_Review")
].copy()

borderline_df = borderline_df.sort_values(
    ["best_score", "score_margin"],
    ascending=[False, True]
)

print("Borderline / Review cases:", len(borderline_df))

display(borderline_df)

Borderline / Review cases: 43

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
284,38858,19.930050,79.120400,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.000000,1.000000,0.099882,0.155377,2.112822,NaN,NaN,23,6
317,39182,23.497204,68.578189,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.294521,0.705479,0.139267,0.245869,1.073055,NaN,NaN,119,20
391,40868,19.936474,73.711858,Needs_Review,Low,0.60,0.00,0.55,0.60,0.55,...,0.053097,0.707965,0.008850,0.188841,3.597486,0.144736,NaN,NaN,93,20
3,29,24.690245,73.002674,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.451923,0.524038,0.095234,600.653677,1.585191,12.064471,8.499625,183,21
285,38859,19.787393,79.063342,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.190476,0.809524,0.145882,13.864859,1.038567,NaN,NaN,20,10
292,38958,15.525906,73.994028,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.210884,0.482993,0.025375,5.719276,1.675976,NaN,NaN,136,21
252,38646,15.658527,73.988879,Needs_Review,Low,0.45,0.15,0.55,0.55,0.45,...,0.000000,0.395225,0.000000,0.078169,12.829935,0.990898,NaN,NaN,285,22
447,48131,18.717034,73.858276,Other_Persistent_Thermal_Source,Low,0.45,0.45,0.30,0.45,0.45,...,0.357143,0.214286,0.000000,0.481220,13.234756,3.185714,NaN,NaN,11,6
5,31,23.315243,70.487057,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.052632,0.060729,0.862348,0.169107,5.543293,20.084768,211.404492,193.959031,228,23
6,32,23.304789,70.476777,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.156250,0.843750,0.206351,4.351976,20.651400,212.969854,195.521549,33,13
16,80,23.170343,70.218120,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.300000,0.600000,0.131049,3.087866,11.095306,241.657773,223.888965,20,8
17,81,23.105164,70.188032,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.330000,0.660000,0.194546,7.352366,15.180115,249.091727,231.390368,98,19
40,523,23.013945,70.102891,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.019048,0.176190,0.771429,0.102608,10.027297,8.534281,NaN,NaN,177,19
53,969,27.467406,71.981374,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.000000,1.000000,0.347843,529.352336,94.042167,47.989042,29.863074,11,9
60,1265,28.251841,73.249360,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.000000,1.000000,0.467078,390.509353,31.386554,22.298924,22.597211,16,8
230,38611,21.105104,72.640954,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.328869,0.671131,0.276135,1.613707,52.566936,NaN,NaN,578,24
268,38786,21.233418,79.629771,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.367347,0.629252,0.249435,16.733453,32.503944,NaN,NaN,228,21
282,38855,22.907231,69.873321,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.062500,0.083333,0.812500,0.169974,2.605528,14.885130,NaN,NaN,46,14
297,39089,20.006386,79.183813,Other_Persistent_Thermal_Source,Low,0.45,0.00,0.30,0.45,0.30,...,0.000000,0.039216,0.921569,1.828686,0.048935,10.899928,NaN,NaN,46,10
499,59472,20.129992,79.112149,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.30,0.45,0.30,...,0.388889,0.000000,0.314815,7.899936,15.698638,1.756776,NaN,NaN,49,11
256,38706,21.683964,72.536954,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.10,0.45,0.15,...,0.000000,0.058824,0.352941,0.158078,4.864759,33.627793,NaN,NaN,20,6
365,40112,21.342496,72.998922,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.10,0.45,0.15,...,0.238095,0.000000,0.285714,0.889591,0.165534,7.603277,NaN,NaN,10,8
439,45180,21.693999,72.604870,Other_Persistent_Thermal_Source,Low,0.45,0.15,0.10,0.45,0.15,...,0.333333,0.190476,0.000000,0.050578,1.206592,40.568015,NaN,NaN,10,8
540,63191,21.066649,72.886287,Other_Persistent_Thermal_Source,Low,0.00,0.45,0.00,0.45,0.00,...,0.384615,0.230769,0.000000,2.328493,9.003823,37.418597,NaN,NaN,10,7
2,28,24.821264,73.093785,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.30,0.40,0.30,...,0.000000,0.733129,0.266871,0.501288,583.763570,1.702899,6.729748,3.341023,282,24
288,38900,22.787922,70.917860,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.30,0.40,0.30,...,0.081081,0.567568,0.324324,0.726165,6.953870,1.834947,NaN,NaN,34,11
331,39355,19.082186,73.035597,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.30,0.40,0.30,...,0.000000,0.708333,0.041667,0.954160,8.603407,1.093482,NaN,NaN,23,12
487,57692,18.456401,73.944091,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.30,0.40,0.30,...,0.000000,1.000000,0.000000,0.981622,9.002225,4.420931,NaN,NaN,21,12
357,39952,18.820330,73.288877,Other_Persistent_Thermal_Source,Low,0.25,0.15,0.40,0.40,0.25,...,0.000000,0.285714,0.000000,0.957335,6.276317,3.832147,NaN,NaN,10,6
264,38765,18.323032,73.324170,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.40,0.40,0.15,...,0.000000,0.000000,0.000000,7.093965,10.330999,1.243336,NaN,NaN,19,9
299,39096,18.369104,73.291764,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.40,0.40,0.15,...,0.000000,0.000000,0.000000,5.456982,8.558911,3.317185,NaN,NaN,13,8
422,42832,19.503330,73.590765,Other_Persistent_Thermal_Source,Low,0.00,0.15,0.40,0.40,0.15,...,0.000000,0.000000,0.000000,2.277942,6.981300,4.487946,NaN,NaN,10,6
9,35,23.118267,70.084872,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.859504,0.132231,0.647935,1.751156,6.826338,255.188344,237.282468,135,22
24,150,29.909731,74.949037,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.330508,0.411017,0.182203,1.093745,156.625245,63.165110,33.891244,8.290464,146,23
73,1611,28.828508,77.155422,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.133333,0.866667,0.000000,1.924938,16.705143,47.567620,4.763114,3.001412,22,11
80,1918,29.475278,76.858158,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.193548,0.483871,0.064516,0.981479,94.192663,92.192991,2.912699,7.022535,22,8
86,2220,25.155066,76.179023,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.800000,0.000000,0.690422,391.518186,48.116661,29.737889,26.811968,11,6
98,2974,28.819840,77.164795,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.227273,0.772727,0.000000,1.676527,15.496888,46.528372,5.052450,3.730764,21,9
118,6067,28.346604,77.257296,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.962963,0.037037,1.370723,22.504046,5.165401,4.232781,3.814104,26,8
245,38633,21.759914,71.950280,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.173913,0.826087,0.000000,0.502732,13.258698,28.141034,NaN,NaN,25,12
257,38707,21.099409,72.844642,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.937500,0.000000,1.419093,10.295067,36.918232,NaN,NaN,20,8
307,39123,22.365439,73.116067,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.000000,0.936170,0.000000,0.616093,1.447780,34.138781,NaN,NaN,158,21
324,39256,20.355694,72.949392,Other_Persistent_Thermal_Source,Low,0.40,0.00,0.00,0.40,0.00,...,0.018519,0.703704,0.000000,1.051274,10.264520,12.048941,NaN,NaN,46,15

In [ ]:
# ============================================================
# SHOW ALL 43 NEEDS_REVIEW
# ============================================================

review_df = evidence_df[
    evidence_df["provisional_label"] == "Needs_Review"
].copy()

review_df = review_df.sort_values(
    ["score_margin", "best_score"],
    ascending=[True, False]
)

display(review_df)

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,provisional_label,label_confidence,industrial_score,agriculture_score,mining_score,best_score,second_best_score,...,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,distance_to_fuel_storage_km,distance_to_agriculture_km,unique_days,unique_months
391,40868,19.936474,73.711858,Needs_Review,Low,0.60,0.00,0.55,0.60,0.55,...,0.053097,0.707965,0.008850,0.188841,3.597486,0.144736,NaN,NaN,93,20
284,38858,19.930050,79.120400,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.000000,1.000000,0.099882,0.155377,2.112822,NaN,NaN,23,6
317,39182,23.497204,68.578189,Needs_Review,Low,0.65,0.00,0.60,0.65,0.60,...,0.000000,0.294521,0.705479,0.139267,0.245869,1.073055,NaN,NaN,119,20
252,38646,15.658527,73.988879,Needs_Review,Low,0.45,0.15,0.55,0.55,0.45,...,0.000000,0.395225,0.000000,0.078169,12.829935,0.990898,NaN,NaN,285,22
3,29,24.690245,73.002674,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.451923,0.524038,0.095234,600.653677,1.585191,12.064471,8.499625,183,21
285,38859,19.787393,79.063342,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.190476,0.809524,0.145882,13.864859,1.038567,NaN,NaN,20,10
292,38958,15.525906,73.994028,Needs_Review,Low,0.45,0.00,0.60,0.60,0.45,...,0.000000,0.210884,0.482993,0.025375,5.719276,1.675976,NaN,NaN,136,21

In [ ]:
# ============================================================
# RESOLVE CLEAR REVIEW CASES
# ============================================================

# Strong industrial evidence
industrial_ids = [40868, 38858, 39182]

# Strong enough mining evidence
mining_ids = [38646]

df.loc[
    df["HOTSPOT_ID"].isin(industrial_ids),
    "provisional_label"
] = "Industrial"

df.loc[
    df["HOTSPOT_ID"].isin(mining_ids),
    "provisional_label"
] = "Mining_Extraction"

# Update confidence
df.loc[
    df["HOTSPOT_ID"].isin([38858, 39182]),
    "label_confidence"
] = "High"

df.loc[
    df["HOTSPOT_ID"].isin([40868, 38646]),
    "label_confidence"
] = "Medium"

In [ ]:
# ============================================================
# SHOW THE 3 FINAL AMBIGUOUS HOTSPOTS
# ============================================================

final_review_ids = [29, 38859, 38958]

final_review = df[
    df["HOTSPOT_ID"].isin(final_review_ids)
].copy()

cols = [
    "HOTSPOT_ID",
    "hotspot_latitude",
    "hotspot_longitude",
    "dominant_land_cover",

    "industrial_score",
    "agriculture_score",
    "mining_score",

    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",

    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_bare_ratio",

    "unique_days",
    "unique_months"
]

cols = [c for c in cols if c in final_review.columns]

display(final_review[cols])

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,dominant_land_cover,industrial_score,agriculture_score,mining_score,distance_to_industrial_km,distance_to_power_km,distance_to_mining_km,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,unique_days,unique_months
3,29,24.690245,73.002674,bare,0.45,0.0,0.6,0.095234,600.653677,1.585191,0.0,0.451923,0.524038,183,21
285,38859,19.787393,79.063342,bare,0.45,0.0,0.6,0.145882,13.864859,1.038567,0.0,0.190476,0.809524,20,10
292,38958,15.525906,73.994028,bare,0.45,0.0,0.6,0.025375,5.719276,1.675976,0.0,0.210884,0.482993,136,21

In [ ]:
# ============================================================
# RESOLVE FINAL 3 AMBIGUOUS HOTSPOTS
# ============================================================

final_industrial_ids = [29, 38859, 38958]

df.loc[
    df["HOTSPOT_ID"].isin(final_industrial_ids),
    "provisional_label"
] = "Industrial"

df.loc[
    df["HOTSPOT_ID"].isin(final_industrial_ids),
    "label_confidence"
] = "Medium"

print(
    df["provisional_label"].value_counts()
)

provisional_label
Agricultural_Vegetation            264
Other_Persistent_Thermal_Source    170
Industrial                          62
Needs_Review                        36
Mining_Extraction                   20
Name: count, dtype: int64

In [ ]:
print(
    "\nNeeds Review remaining:",
    (df["provisional_label"] == "Needs_Review").sum()
)

display(
    df[df["provisional_label"] == "Needs_Review"]
)

Needs Review remaining: 36

,HOTSPOT_ID,total_detections,unique_days,unique_months,first_detection,last_detection,mean_FRP,max_FRP,active_duration_days,hotspot_latitude,...,weather_observations,industrial_score,agriculture_score,mining_score,best_score,second_best_score,score_margin,evidence_class,label_confidence,provisional_label
2,28,326,282,24,2024-01-01,2025-12-30,1.388344,5.13,730,24.821264,...,326.0,0.40,0.00,0.3,0.40,0.30,0.10,Industrial,Low,Needs_Review
5,31,247,228,23,2024-01-01,2025-12-28,1.134939,4.82,728,23.315243,...,247.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
6,32,33,33,13,2024-01-01,2025-12-21,0.876061,1.55,721,23.304789,...,32.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
9,35,200,135,22,2024-01-01,2025-12-30,2.180950,17.93,730,23.118267,...,121.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
16,80,20,20,8,2024-01-02,2025-12-27,0.676500,1.02,726,23.170343,...,20.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
17,81,100,98,19,2024-01-02,2025-12-29,0.908200,5.67,728,23.105164,...,100.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
24,150,316,146,23,2024-01-04,2025-12-19,4.113576,37.68,716,29.909731,...,236.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
40,523,217,177,19,2024-01-01,2025-09-12,1.106267,10.40,621,23.013945,...,210.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
53,969,225,11,9,2024-01-24,2025-12-28,8.186844,37.06,705,27.467406,...,2.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
60,1265,737,16,8,2024-02-04,2025-11-16,4.344573,73.82,652,28.251841,...,13.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
73,1611,23,22,11,2024-02-14,2025-12-12,0.478696,1.24,668,28.828508,...,15.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
80,1918,33,22,8,2024-02-22,2025-08-31,3.105455,27.22,557,29.475278,...,31.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
86,2220,15,11,6,2024-03-01,2025-04-01,1.790667,4.23,397,25.155066,...,10.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
98,2974,22,21,9,2024-03-20,2025-12-22,0.709091,1.28,643,28.819840,...,22.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
118,6067,28,26,8,2024-04-17,2025-12-30,0.620357,1.18,623,28.346604,...,27.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
230,38611,4764,578,24,2024-01-01,2025-12-31,5.582639,55.27,731,21.105104,...,1344.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
245,38633,25,25,12,2024-01-01,2025-12-19,0.613200,1.24,719,21.759914,...,23.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
256,38706,34,20,6,2024-01-02,2025-03-04,2.354706,15.09,428,21.683964,...,17.0,0.45,0.15,0.1,0.45,0.15,0.30,Industrial,Low,Needs_Review
257,38707,31,20,8,2024-01-02,2025-12-23,4.163226,15.11,722,21.099409,...,16.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
264,38765,34,19,9,2024-01-03,2025-12-30,6.171765,16.15,728,18.323032,...,5.0,0.00,0.15,0.4,0.40,0.15,0.25,Mining_Extraction,Low,Needs_Review
268,38786,294,228,21,2024-01-03,2025-12-31,1.524830,7.61,729,21.233418,...,294.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
282,38855,48,46,14,2024-01-04,2025-12-27,0.836458,5.37,724,22.907231,...,48.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
288,38900,45,34,11,2024-01-05,2025-04-05,1.242222,4.38,457,22.787922,...,37.0,0.40,0.00,0.3,0.40,0.30,0.10,Industrial,Low,Needs_Review
297,39089,56,46,10,2024-01-08,2025-12-25,0.682143,1.17,718,20.006386,...,51.0,0.45,0.00,0.3,0.45,0.30,0.15,Industrial,Low,Needs_Review
299,39096,22,13,8,2024-01-08,2025-12-09,5.888182,15.73,702,18.369104,...,4.0,0.00,0.15,0.4,0.40,0.15,0.25,Mining_Extraction,Low,Needs_Review
307,39123,225,158,21,2024-01-10,2025-12-30,2.250667,10.63,721,22.365439,...,188.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
324,39256,55,46,15,2024-01-12,2025-12-25,1.108182,3.08,714,20.355694,...,54.0,0.40,0.00,0.0,0.40,0.00,0.40,Industrial,Low,Needs_Review
331,39355,24,23,12,2024-01-13,2025-12-27,0.869583,1.52,715,19.082186,...,24.0,0.40,0.00,0.3,0.40,0.30,0.10,Industrial,Low,Needs_Review
357,39952,14,10,6,2024-01-22,2025-12-19,6.083571,14.77,698,18.820330,...,7.0,0.25,0.15,0.4,0.40,0.25,0.15,Mining_Extraction,Low,Needs_Review
365,40112,38,10,8,2024-01-24,2025-12-07,4.052895,12.12,684,21.342496,...,21.0,0.45,0.15,0.1,0.45,0.15,0.30,Industrial,Low,Needs_Review
422,42832,26,10,6,2024-02-19,2025-12-12,1.633077,3.96,663,19.503330,...,7.0,0.00,0.15,0.4,0.40,0.15,0.25,Mining_Extraction,Low,Needs_Review
439,45180,23,10,8,2024-03-05,2025-12-04,5.389130,54.01,640,21.693999,...,21.0,0.45,0.15,0.1,0.45,0.15,0.30,Industrial,Low,Needs_Review
447,48131,14,11,6,2024-03-16,2025-04-21,2.185714,5.10,402,18.717034,...,14.0,0.45,0.45,0.3,0.45,0.45,0.00,Industrial,Low,Needs_Review
487,57692,24,21,12,2024-04-07,2025-12-24,0.926667,4.65,627,18.456401,...,22.0,0.40,0.00,0.3,0.40,0.30,0.10,Industrial,Low,Needs_Review
499,59472,54,49,11,2024-04-16,2025-12-31,0.801852,2.78,625,20.129992,...,54.0,0.00,0.45,0.3,0.45,0.30,0.15,Agricultural_Vegetation,Low,Needs_Review
540,63191,13,10,7,2024-05-09,2025-12-01,1.232308,3.41,572,21.066649,...,13.0,0.00,0.45,0.0,0.45,0.00,0.45,Agricultural_Vegetation,Low,Needs_Review

In [ ]:
# ============================================================
# DETAILED REVIEW OF REMAINING HOTSPOTS
# ============================================================

review_df = df[
    df["provisional_label"] == "Needs_Review"
].copy()

review_cols = [
    "HOTSPOT_ID",
    "hotspot_latitude",
    "hotspot_longitude",

    "dominant_land_cover",

    # Scores
    "industrial_score",
    "agriculture_score",
    "mining_score",
    "best_score",
    "second_best_score",
    "score_margin",

    # OSM distances
    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",

    # Land cover
    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_bare_ratio",
    "lc_trees_ratio",
    "lc_grass_ratio",
    "lc_shrub_and_scrub_ratio",

    # Persistence
    "unique_days",
    "unique_months"
]

# Only keep columns that actually exist
review_cols = [
    c for c in review_cols
    if c in review_df.columns
]

review_df = review_df[review_cols].copy()

# Sort AFTER best_score and score_margin have been retained
review_df = review_df.sort_values(
    ["best_score", "score_margin"],
    ascending=[False, True]
)

print("Remaining review cases:", len(review_df))

display(review_df)

Remaining review cases: 36

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,dominant_land_cover,industrial_score,agriculture_score,mining_score,best_score,second_best_score,score_margin,...,distance_to_fuel_storage_km,distance_to_agriculture_km,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,lc_shrub_and_scrub_ratio,unique_days,unique_months
447,48131,18.717034,73.858276,crops,0.45,0.45,0.3,0.45,0.45,0.00,...,NaN,NaN,0.357143,0.214286,0.000000,0.071429,0.071429,0.285714,11,6
5,31,23.315243,70.487057,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,211.404492,193.959031,0.052632,0.060729,0.862348,0.000000,0.000000,0.024291,228,23
6,32,23.304789,70.476777,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,212.969854,195.521549,0.000000,0.156250,0.843750,0.000000,0.000000,0.000000,33,13
16,80,23.170343,70.218120,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,241.657773,223.888965,0.000000,0.300000,0.600000,0.000000,0.000000,0.100000,20,8
17,81,23.105164,70.188032,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,249.091727,231.390368,0.000000,0.330000,0.660000,0.000000,0.000000,0.000000,98,19
40,523,23.013945,70.102891,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.019048,0.176190,0.771429,0.028571,0.000000,0.004762,177,19
53,969,27.467406,71.981374,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,47.989042,29.863074,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,11,9
60,1265,28.251841,73.249360,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,22.298924,22.597211,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,16,8
230,38611,21.105104,72.640954,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.328869,0.671131,0.000000,0.000000,0.000000,578,24
268,38786,21.233418,79.629771,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.367347,0.629252,0.003401,0.000000,0.000000,228,21
282,38855,22.907231,69.873321,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.062500,0.083333,0.812500,0.041667,0.000000,0.000000,46,14
297,39089,20.006386,79.183813,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.039216,0.921569,0.039216,0.000000,0.000000,46,10
499,59472,20.129992,79.112149,crops,0.00,0.45,0.3,0.45,0.30,0.15,...,NaN,NaN,0.388889,0.000000,0.314815,0.000000,0.092593,0.000000,49,11
256,38706,21.683964,72.536954,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.000000,0.058824,0.352941,0.000000,0.000000,0.470588,20,6
365,40112,21.342496,72.998922,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.238095,0.000000,0.285714,0.047619,0.000000,0.428571,10,8
439,45180,21.693999,72.604870,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.333333,0.190476,0.000000,0.142857,0.000000,0.333333,10,8
540,63191,21.066649,72.886287,crops,0.00,0.45,0.0,0.45,0.00,0.45,...,NaN,NaN,0.384615,0.230769,0.000000,0.307692,0.000000,0.000000,10,7
2,28,24.821264,73.093785,built,0.40,0.00,0.3,0.40,0.30,0.10,...,6.729748,3.341023,0.000000,0.733129,0.266871,0.000000,0.000000,0.000000,282,24
288,38900,22.787922,70.917860,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.081081,0.567568,0.324324,0.000000,0.000000,0.027027,34,11
331,39355,19.082186,73.035597,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.000000,0.708333,0.041667,0.041667,0.000000,0.000000,23,12
487,57692,18.456401,73.944091,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,21,12
357,39952,18.820330,73.288877,shrub_and_scrub,0.25,0.15,0.4,0.40,0.25,0.15,...,NaN,NaN,0.000000,0.285714,0.000000,0.285714,0.000000,0.428571,10,6
264,38765,18.323032,73.324170,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.400000,0.000000,0.600000,19,9
299,39096,18.369104,73.291764,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,13,8
422,42832,19.503330,73.590765,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.142857,0.000000,0.857143,10,6
9,35,23.118267,70.084872,built,0.40,0.00,0.0,0.40,0.00,0.40,...,255.188344,237.282468,0.000000,0.859504,0.132231,0.008264,0.000000,0.000000,135,22
24,150,29.909731,74.949037,built,0.40,0.00,0.0,0.40,0.00,0.40,...,33.891244,8.290464,0.330508,0.411017,0.182203,0.076271,0.000000,0.000000,146,23
73,1611,28.828508,77.155422,built,0.40,0.00,0.0,0.40,0.00,0.40,...,4.763114,3.001412,0.133333,0.866667,0.000000,0.000000,0.000000,0.000000,22,11
80,1918,29.475278,76.858158,built,0.40,0.00,0.0,0.40,0.00,0.40,...,2.912699,7.022535,0.193548,0.483871,0.064516,0.000000,0.000000,0.000000,22,8
86,2220,25.155066,76.179023,built,0.40,0.00,0.0,0.40,0.00,0.40,...,29.737889,26.811968,0.000000,0.800000,0.000000,0.200000,0.000000,0.000000,11,6
98,2974,28.819840,77.164795,built,0.40,0.00,0.0,0.40,0.00,0.40,...,5.052450,3.730764,0.227273,0.772727,0.000000,0.000000,0.000000,0.000000,21,9
118,6067,28.346604,77.257296,built,0.40,0.00,0.0,0.40,0.00,0.40,...,4.232781,3.814104,0.000000,0.962963,0.037037,0.000000,0.000000,0.000000,26,8
245,38633,21.759914,71.950280,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.173913,0.826087,0.000000,0.000000,0.000000,0.000000,25,12
257,38707,21.099409,72.844642,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.000000,0.937500,0.000000,0.000000,0.000000,0.000000,20,8
307,39123,22.365439,73.116067,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.000000,0.936170,0.000000,0.063830,0.000000,0.000000,158,21
324,39256,20.355694,72.949392,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.018519,0.703704,0.000000,0.259259,0.000000,0.000000,46,15

In [ ]:
print("========== REVIEW BY EVIDENCE CLASS ==========")

print(
    review_df["evidence_class"].value_counts()
)

print("\n========== REVIEW BY LAND COVER ==========")

print(
    review_df["dominant_land_cover"].value_counts(
        dropna=False
    )
)

========== REVIEW BY EVIDENCE CLASS ==========

KeyError: 'evidence_class'

In [ ]:
print("========== REVIEW BY EVIDENCE CLASS ==========")

print(
    review_df["evidence_class"].value_counts()
)

print("\n========== REVIEW BY LAND COVER ==========")

print(
    review_df["dominant_land_cover"].value_counts(
        dropna=False
    )
)

========== REVIEW BY EVIDENCE CLASS ==========

KeyError: 'evidence_class'

In [ ]:
# ============================================================
# REVIEW THE REMAINING NEEDS_REVIEW HOTSPOTS
# ============================================================

review_df = df[
    df["provisional_label"] == "Needs_Review"
].copy()

review_cols = [
    "HOTSPOT_ID",
    "hotspot_latitude",
    "hotspot_longitude",

    "dominant_land_cover",

    "industrial_score",
    "agriculture_score",
    "mining_score",

    "best_score",
    "second_best_score",
    "score_margin",

    "distance_to_industrial_km",
    "distance_to_power_km",
    "distance_to_mining_km",
    "distance_to_fuel_storage_km",
    "distance_to_agriculture_km",

    "lc_crops_ratio",
    "lc_built_ratio",
    "lc_bare_ratio",
    "lc_trees_ratio",
    "lc_grass_ratio",
    "lc_shrub_and_scrub_ratio",

    "unique_days",
    "unique_months"
]

# Keep only columns that exist
review_cols = [
    c for c in review_cols
    if c in review_df.columns
]

review_df = review_df[review_cols].copy()

# Sort by strongest evidence
if "best_score" in review_df.columns:
    review_df = review_df.sort_values(
        ["best_score", "score_margin"],
        ascending=[False, True]
    )

print("Remaining Needs_Review:", len(review_df))

display(review_df)

Remaining Needs_Review: 36

,HOTSPOT_ID,hotspot_latitude,hotspot_longitude,dominant_land_cover,industrial_score,agriculture_score,mining_score,best_score,second_best_score,score_margin,...,distance_to_fuel_storage_km,distance_to_agriculture_km,lc_crops_ratio,lc_built_ratio,lc_bare_ratio,lc_trees_ratio,lc_grass_ratio,lc_shrub_and_scrub_ratio,unique_days,unique_months
447,48131,18.717034,73.858276,crops,0.45,0.45,0.3,0.45,0.45,0.00,...,NaN,NaN,0.357143,0.214286,0.000000,0.071429,0.071429,0.285714,11,6
5,31,23.315243,70.487057,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,211.404492,193.959031,0.052632,0.060729,0.862348,0.000000,0.000000,0.024291,228,23
6,32,23.304789,70.476777,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,212.969854,195.521549,0.000000,0.156250,0.843750,0.000000,0.000000,0.000000,33,13
16,80,23.170343,70.218120,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,241.657773,223.888965,0.000000,0.300000,0.600000,0.000000,0.000000,0.100000,20,8
17,81,23.105164,70.188032,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,249.091727,231.390368,0.000000,0.330000,0.660000,0.000000,0.000000,0.000000,98,19
40,523,23.013945,70.102891,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.019048,0.176190,0.771429,0.028571,0.000000,0.004762,177,19
53,969,27.467406,71.981374,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,47.989042,29.863074,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,11,9
60,1265,28.251841,73.249360,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,22.298924,22.597211,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,16,8
230,38611,21.105104,72.640954,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.328869,0.671131,0.000000,0.000000,0.000000,578,24
268,38786,21.233418,79.629771,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.367347,0.629252,0.003401,0.000000,0.000000,228,21
282,38855,22.907231,69.873321,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.062500,0.083333,0.812500,0.041667,0.000000,0.000000,46,14
297,39089,20.006386,79.183813,bare,0.45,0.00,0.3,0.45,0.30,0.15,...,NaN,NaN,0.000000,0.039216,0.921569,0.039216,0.000000,0.000000,46,10
499,59472,20.129992,79.112149,crops,0.00,0.45,0.3,0.45,0.30,0.15,...,NaN,NaN,0.388889,0.000000,0.314815,0.000000,0.092593,0.000000,49,11
256,38706,21.683964,72.536954,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.000000,0.058824,0.352941,0.000000,0.000000,0.470588,20,6
365,40112,21.342496,72.998922,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.238095,0.000000,0.285714,0.047619,0.000000,0.428571,10,8
439,45180,21.693999,72.604870,shrub_and_scrub,0.45,0.15,0.1,0.45,0.15,0.30,...,NaN,NaN,0.333333,0.190476,0.000000,0.142857,0.000000,0.333333,10,8
540,63191,21.066649,72.886287,crops,0.00,0.45,0.0,0.45,0.00,0.45,...,NaN,NaN,0.384615,0.230769,0.000000,0.307692,0.000000,0.000000,10,7
2,28,24.821264,73.093785,built,0.40,0.00,0.3,0.40,0.30,0.10,...,6.729748,3.341023,0.000000,0.733129,0.266871,0.000000,0.000000,0.000000,282,24
288,38900,22.787922,70.917860,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.081081,0.567568,0.324324,0.000000,0.000000,0.027027,34,11
331,39355,19.082186,73.035597,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.000000,0.708333,0.041667,0.041667,0.000000,0.000000,23,12
487,57692,18.456401,73.944091,built,0.40,0.00,0.3,0.40,0.30,0.10,...,NaN,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,21,12
357,39952,18.820330,73.288877,shrub_and_scrub,0.25,0.15,0.4,0.40,0.25,0.15,...,NaN,NaN,0.000000,0.285714,0.000000,0.285714,0.000000,0.428571,10,6
264,38765,18.323032,73.324170,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.400000,0.000000,0.600000,19,9
299,39096,18.369104,73.291764,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,13,8
422,42832,19.503330,73.590765,shrub_and_scrub,0.00,0.15,0.4,0.40,0.15,0.25,...,NaN,NaN,0.000000,0.000000,0.000000,0.142857,0.000000,0.857143,10,6
9,35,23.118267,70.084872,built,0.40,0.00,0.0,0.40,0.00,0.40,...,255.188344,237.282468,0.000000,0.859504,0.132231,0.008264,0.000000,0.000000,135,22
24,150,29.909731,74.949037,built,0.40,0.00,0.0,0.40,0.00,0.40,...,33.891244,8.290464,0.330508,0.411017,0.182203,0.076271,0.000000,0.000000,146,23
73,1611,28.828508,77.155422,built,0.40,0.00,0.0,0.40,0.00,0.40,...,4.763114,3.001412,0.133333,0.866667,0.000000,0.000000,0.000000,0.000000,22,11
80,1918,29.475278,76.858158,built,0.40,0.00,0.0,0.40,0.00,0.40,...,2.912699,7.022535,0.193548,0.483871,0.064516,0.000000,0.000000,0.000000,22,8
86,2220,25.155066,76.179023,built,0.40,0.00,0.0,0.40,0.00,0.40,...,29.737889,26.811968,0.000000,0.800000,0.000000,0.200000,0.000000,0.000000,11,6
98,2974,28.819840,77.164795,built,0.40,0.00,0.0,0.40,0.00,0.40,...,5.052450,3.730764,0.227273,0.772727,0.000000,0.000000,0.000000,0.000000,21,9
118,6067,28.346604,77.257296,built,0.40,0.00,0.0,0.40,0.00,0.40,...,4.232781,3.814104,0.000000,0.962963,0.037037,0.000000,0.000000,0.000000,26,8
245,38633,21.759914,71.950280,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.173913,0.826087,0.000000,0.000000,0.000000,0.000000,25,12
257,38707,21.099409,72.844642,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.000000,0.937500,0.000000,0.000000,0.000000,0.000000,20,8
307,39123,22.365439,73.116067,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.000000,0.936170,0.000000,0.063830,0.000000,0.000000,158,21
324,39256,20.355694,72.949392,built,0.40,0.00,0.0,0.40,0.00,0.40,...,NaN,NaN,0.018519,0.703704,0.000000,0.259259,0.000000,0.000000,46,15

In [ ]:
# ============================================================
# WHAT IS THE STRONGEST EVIDENCE FOR EACH REVIEW CASE?
# ============================================================

score_columns = [
    "industrial_score",
    "agriculture_score",
    "mining_score"
]

score_columns = [
    c for c in score_columns
    if c in review_df.columns
]

review_df["strongest_score"] = review_df[score_columns].max(axis=1)

review_df["strongest_category"] = (
    review_df[score_columns]
    .idxmax(axis=1)
    .str.replace("_score", "", regex=False)
)

print("\n========== STRONGEST EVIDENCE ==========\n")

print(
    review_df["strongest_category"].value_counts()
)

display(
    review_df[
        [
            "HOTSPOT_ID",
            "strongest_category",
            "strongest_score",
            "dominant_land_cover",
            "distance_to_industrial_km",
            "distance_to_mining_km",
            "distance_to_power_km",
            "unique_days",
            "unique_months"
        ]
    ]
)

========== STRONGEST EVIDENCE ==========

strongest_category
industrial     30
mining          4
agriculture     2
Name: count, dtype: int64

,HOTSPOT_ID,strongest_category,strongest_score,dominant_land_cover,distance_to_industrial_km,distance_to_mining_km,distance_to_power_km,unique_days,unique_months
447,48131,industrial,0.45,crops,0.481220,3.185714,13.234756,11,6
5,31,industrial,0.45,bare,0.169107,20.084768,5.543293,228,23
6,32,industrial,0.45,bare,0.206351,20.651400,4.351976,33,13
16,80,industrial,0.45,bare,0.131049,11.095306,3.087866,20,8
17,81,industrial,0.45,bare,0.194546,15.180115,7.352366,98,19
40,523,industrial,0.45,bare,0.102608,8.534281,10.027297,177,19
53,969,industrial,0.45,bare,0.347843,94.042167,529.352336,11,9
60,1265,industrial,0.45,bare,0.467078,31.386554,390.509353,16,8
230,38611,industrial,0.45,bare,0.276135,52.566936,1.613707,578,24
268,38786,industrial,0.45,bare,0.249435,32.503944,16.733453,228,21
282,38855,industrial,0.45,bare,0.169974,14.885130,2.605528,46,14
297,39089,industrial,0.45,bare,1.828686,10.899928,0.048935,46,10
499,59472,agriculture,0.45,crops,7.899936,1.756776,15.698638,49,11
256,38706,industrial,0.45,shrub_and_scrub,0.158078,33.627793,4.864759,20,6
365,40112,industrial,0.45,shrub_and_scrub,0.889591,7.603277,0.165534,10,8
439,45180,industrial,0.45,shrub_and_scrub,0.050578,40.568015,1.206592,10,8
540,63191,agriculture,0.45,crops,2.328493,37.418597,9.003823,10,7
2,28,industrial,0.40,built,0.501288,1.702899,583.763570,282,24
288,38900,industrial,0.40,built,0.726165,1.834947,6.953870,34,11
331,39355,industrial,0.40,built,0.954160,1.093482,8.603407,23,12
487,57692,industrial,0.40,built,0.981622,4.420931,9.002225,21,12
357,39952,mining,0.40,shrub_and_scrub,0.957335,3.832147,6.276317,10,6
264,38765,mining,0.40,shrub_and_scrub,7.093965,1.243336,10.330999,19,9
299,39096,mining,0.40,shrub_and_scrub,5.456982,3.317185,8.558911,13,8
422,42832,mining,0.40,shrub_and_scrub,2.277942,4.487946,6.981300,10,6
9,35,industrial,0.40,built,0.647935,6.826338,1.751156,135,22
24,150,industrial,0.40,built,1.093745,63.165110,156.625245,146,23
73,1611,industrial,0.40,built,1.924938,47.567620,16.705143,22,11
80,1918,industrial,0.40,built,0.981479,92.192991,94.192663,22,8
86,2220,industrial,0.40,built,0.690422,48.116661,391.518186,11,6
98,2974,industrial,0.40,built,1.676527,46.528372,15.496888,21,9
118,6067,industrial,0.40,built,1.370723,5.165401,22.504046,26,8
245,38633,industrial,0.40,built,0.502732,28.141034,13.258698,25,12
257,38707,industrial,0.40,built,1.419093,36.918232,10.295067,20,8
307,39123,industrial,0.40,built,0.616093,34.138781,1.447780,158,21
324,39256,industrial,0.40,built,1.051274,12.048941,10.264520,46,15

In [ ]:
# ============================================================
# RESOLVE THE REMAINING 36 REVIEW CASES
# ============================================================

# 30 Industrial
industrial_review_ids = [
    48131, 31, 32, 80, 81, 523, 969, 1265,
    38611, 38786, 38855, 39089, 38706, 40112,
    45180, 28, 38900, 39355, 57692, 35,
    150, 1611, 1918, 2220, 2974, 6067,
    38633, 38707, 39123, 39256
]

# 4 Mining
mining_review_ids = [
    39952,
    38765,
    39096,
    42832
]

# 2 Agriculture
agriculture_review_ids = [
    59472,
    63191
]


# Apply labels
df.loc[
    df["HOTSPOT_ID"].isin(industrial_review_ids),
    "provisional_label"
] = "Industrial"

df.loc[
    df["HOTSPOT_ID"].isin(mining_review_ids),
    "provisional_label"
] = "Mining_Extraction"

df.loc[
    df["HOTSPOT_ID"].isin(agriculture_review_ids),
    "provisional_label"
] = "Agricultural_Vegetation"


# Confidence
df.loc[
    df["HOTSPOT_ID"].isin(industrial_review_ids),
    "label_confidence"
] = "Medium"

df.loc[
    df["HOTSPOT_ID"].isin(mining_review_ids),
    "label_confidence"
] = "Medium"

df.loc[
    df["HOTSPOT_ID"].isin(agriculture_review_ids),
    "label_confidence"
] = "Medium"


# ============================================================
# CHECK
# ============================================================

print("========== FINAL LABEL CHECK ==========")

print(df["provisional_label"].value_counts())

print("\nNeeds Review remaining:")

print(
    (df["provisional_label"] == "Needs_Review").sum()
)

========== FINAL LABEL CHECK ==========
provisional_label
Agricultural_Vegetation            266
Other_Persistent_Thermal_Source    170
Industrial                          92
Mining_Extraction                   24
Name: count, dtype: int64

Needs Review remaining:
0

In [ ]:
df["provisional_label"].value_counts()

provisional_label
Agricultural_Vegetation            266
Other_Persistent_Thermal_Source    170
Industrial                          92
Mining_Extraction                   24
Name: count, dtype: int64

In [ ]:
# ============================================================
# CREATE FINAL LABEL COLUMNS
# ============================================================

df["FINAL_LABEL"] = df["provisional_label"]

# All current labels are rule/evidence based
df["LABEL_SOURCE"] = "rule_based_evidence"

# The 36 cases we explicitly reviewed
review_resolved_ids = (
    industrial_review_ids
    + mining_review_ids
    + agriculture_review_ids
    + [29, 38859, 38958]
)

df.loc[
    df["HOTSPOT_ID"].isin(review_resolved_ids),
    "LABEL_SOURCE"
] = "manual_evidence_review"


# Rename confidence column into final form
df["LABEL_CONFIDENCE"] = df["label_confidence"]

In [ ]:
print("========== FINAL DATASET CHECK ==========")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nFinal labels:")
print(df["FINAL_LABEL"].value_counts())

print("\nLabel confidence:")
print(df["LABEL_CONFIDENCE"].value_counts())

print("\nLabel source:")
print(df["LABEL_SOURCE"].value_counts())

print("\nMissing FINAL_LABEL:")
print(df["FINAL_LABEL"].isna().sum())

========== FINAL DATASET CHECK ==========
Rows: 552
Columns: 50

Final labels:
FINAL_LABEL
Agricultural_Vegetation            266
Other_Persistent_Thermal_Source    170
Industrial                          92
Mining_Extraction                   24
Name: count, dtype: int64

Label confidence:
LABEL_CONFIDENCE
High      261
Low       170
Medium    121
Name: count, dtype: int64

Label source:
LABEL_SOURCE
rule_based_evidence       513
manual_evidence_review     39
Name: count, dtype: int64

Missing FINAL_LABEL:
0

In [ ]:
print(
    "Duplicate HOTSPOT_IDs:",
    df["HOTSPOT_ID"].duplicated().sum()
)

Duplicate HOTSPOT_IDs: 0

In [ ]:
final_path = (
    "/content/drive/MyDrive/DataSetForpython/"
    "FINAL_PERSISTENT_HOTSPOT_DATASET.csv"
)

df.to_csv(
    final_path,
    index=False
)

print("🔥 FINAL DATASET SAVED")
print(final_path)

🔥 FINAL DATASET SAVED
/content/drive/MyDrive/DataSetForpython/FINAL_PERSISTENT_HOTSPOT_DATASET.csv